### ISSUE TITLE
Log 404 at Amazon's end with ERROR severity

### ISSUE THREAD

**Issue by garysargentpersonal** [alandtse/alexa_media_player#2088]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**

As of today the last_called attributes are not updating and are all null. I've tried a full system restart, called the service call to update them, but they all remain null.

I'm in the UK Amazon region, and appear to be authenticated - I can send tts to Alexa, but last_called, last_called_timestamp, and last_called_summary are all null.

I just enabled debug logs as encouraged in github and it has shown what the issue is!...

`
2023-10-25 09:01:37.435 DEBUG (MainThread) [custom_components.alexa_media.services] Service update_last_called for: [] 2023-10-25 09:01:37.526 DEBUG (MainThread) [alexapy.alexaapi] m***@****************k: static GET: https://alexa.amazon.co.uk/api/activities?startTime=&size=10&offset=1 returned 404:Not Found:text/html 2023-10-25 09:01:37.526 DEBUG (MainThread) [alexapy.alexaapi] Returning None due to status: 404
`

And on going to https://alexa.amazon.co.uk/api/activities there is a message up saying "Our website is currently unavailable while we make some improvements to our service".

That explains that then - however would it be possible to catch the 404 and log it as an error rather than debug to make it obvious to the user that there is an error at Amazon's end?

**Describe the solution you'd like**
Catch the 404 and log it as an error rather than debug to make it obvious to the user that there is an error at Amazon's end.

**Describe alternatives you've considered**
User can enable debug logging and can see the error.

**Additional context**
n/a

**Comment by alandtse** [comment]
Unfortunately much of Alexa's API returns 4xx error codes so we can't have a general position of logging an error as it would flood the logs. For example, media players may return something in the 4xx range if they're currently not playing. That said, activities may be specific enough I'd accept a PR to log the error. Of course it may be moot since it causes issues as mentioned in #2090 so we'd find out anyway.

**Comment by Sir-Udo** [comment]
Hi, at me the same, please help with the 404 error 
"HomeAssistantURL"/auth/alexamedia/proxyverify

**Comment by Pirol62** [comment]
Hi, obviously the new solution doesn't help reliable. Meanwhile I receive this error:
````
Logger: homeassistant.components.script.command_cover_down
Source: helpers/script.py:468
Integration: Skript (documentation, issues)
First occurred: 17:23:39 (1 occurrences)
Last logged: 17:23:39

command_cover_down: Error executing script. Unexpected error for call_service at pos 1: Too Many Requests
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/services.py", line 173, in last_call_handler
    await self.functions.get("update_last_called")(login_obj)
  File "/config/custom_components/alexa_media/helpers.py", line 156, in _catch_login_errors
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 753, in update_last_called
    last_called = await AlexaAPI.get_last_device_serial(login_obj)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 1420, in get_last_device_serial
    response = await AlexaAPI.get_customer_history_records(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 1289, in get_customer_history_records
    response = await AlexaAPI._static_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 338, in _static_request
    return await AlexaAPI._process_response(response, login)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 123, in _process_response
    raise AlexapyTooManyRequestsError(response.reason)
alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests
````
nearly every second service call.
Interesingly this message even appears during the nigt, when no automation or script is calling the service.
So sad....
