### ISSUE TITLE
Alexa Media Player media player not available in new beta

### ISSUE THREAD

**Issue by MJHeijster** [alandtse/alexa_media_player#2149]
**Describe the bug**

Since upgrading to the new 2024.1 beta, the media_player entities are unavailable. The Do not disturb switch still is toggleable.

**To Reproduce**

Go to the integration and check the devices. Some media_player controls are unavailable, some are gone.

I have tried deleting and setting it up again, no result.

**System details**

- Home-assistant (version): **2024.1.0b0**
- alexa_media (version from `const.py` or HA startup): 4.8.1
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : yes

**Logs**
Only thing off I could find was the following:
2023-12-28 16:26:23.362 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up alexa_media platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1275, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1059, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1096, in state_attributes
    if self.support_grouping:
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 986, in support_grouping
    return MediaPlayerEntityFeature.GROUPING in self.supported_features
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

As far as I can tell, this is due to https://developers.home-assistant.io/blog/2022/04/02/support-constants-deprecation/

**Comment by def1149** [comment]
I can confirm the same behavior after updating to 2024.1 beta

**Comment by Petro31** [comment]
formatted:
```
2023-12-28 13:42:50.914 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up alexa_media platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1275, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1059, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1096, in state_attributes
    if self.support_grouping:
       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 986, in support_grouping
    return MediaPlayerEntityFeature.GROUPING in self.supported_features
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
```

**Comment by mhoogenbosch** [comment]
> I can confirm the same behavior after updating to 2024.1 beta

Me too. Watching this.

**Comment by LindsayReid** [comment]
Same here - Alexa media player has temporarily (I hope) gone on strike!

**Comment by def1149** [comment]
.0b1 didn't fix this

Logger: homeassistant.util.logging
Source: util/logging.py:102
First occurred: 5:48:13 PM (303 occurrences)
Last logged: 6:15:22 PM

Exception in _handle_event when dispatching 'alexa_media_xxxxxx': ({'player_state': {'dopplerId': {'deviceSerialNumber': 'xxxxx', 'deviceType': 'xxxxx'}, 'volumeSetting': 20, 'isMuted': False, 'destinationUserId': 'xxxxx'}},) Traceback (most recent call last): File "/config/custom_components/alexa_media/media_player.py", line 407, in _handle_event self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1059, in _async_write_ha_state state, attr, capabilities, shadowed_attr = self.__async_calculate_state() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in __async_calculate_state attr.update(self.state_attributes or {}) ^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1096, in state_attributes if self.support_grouping: ^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 986, in support_grouping return MediaPlayerEntityFeature.GROUPING in self.supported_features ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: argument of type 'int' is not iterable

**Comment by MJHeijster** [comment]
> .0b2 didn't fix it either.

.0b2 fixed the media_player entities for me.

**Comment by def1149** [comment]
After a hard restart, .0b2 seems to have fixed the problem

**Comment by LindsayReid** [comment]
Latest beta has fixed the problem.

Core: 2024.1.0b2
Supervisor: 2023.12.1
Operating System: 11.3.rc1
Frontend: 20231228.0

Many tnanks.

**Comment by Starf0x** [comment]
No fix up to:

Core 2024.1.0b7
Supervisor 2023.12.1
Operating System 11.3.rc2
Frontend 20240103.0

Also not after a 'Hard' Reboot.
