### ISSUE TITLE
Alexa no longer triggers Home Assistant scripts after removing legacy_api_password

### ISSUE THREAD

**Issue by ScottWoolven5** [alandtse/alexa_media_player#2175]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I've previously had this installed for over a year without problems but then started running into Alexa not triggering my Home Assistant scripts around a month ago after I removed the legacy api password from my configuration.yaml. I can't remember exactly what I removed but I was getting notifications that it was going to be obsolete so should remove it. 

When I say something that usually triggers a script, e.g. "Alexa, enable cinema mode", I am seeing an error in the logs. It appears to reference the legacy_api_password. Do I need to add this back to the config? If so what do I need to add, I can't see anything in the wiki about it. 

**To Reproduce**

Say "Alexa, enabled cinema mode". 

**Expected behavior**

I use Alexa to "enable cinema mode" to reduce the brightness of the lounge lights however this no longer occurs. The script does not show that it is triggered.

**System details**

- Home-assistant (version):  
Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4 
- alexa_media (version from `const.py` or HA startup): v4.9.0
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes!

**Logs**

Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 21:32:00 (10 occurrences)
Last logged: 21:41:55

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 95, in handle_req
    resp = await func(view, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/auth/__init__.py", line 265, in post
    return await self._async_handle_refresh_token(hass, data, request.remote)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/auth/__init__.py", line 382, in _async_handle_refresh_token
    access_token = hass.auth.async_create_access_token(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/auth/__init__.py", line 505, in async_create_access_token
    self.async_validate_refresh_token(refresh_token, remote_ip)
  File "/usr/src/homeassistant/homeassistant/auth/__init__.py", line 552, in async_validate_refresh_token
    if provider := self._async_resolve_provider(refresh_token):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/auth/__init__.py", line 538, in _async_resolve_provider
    raise InvalidProvider(
homeassistant.auth.InvalidProvider: Auth provider legacy_api_password, None not available

**Additional context**

**Comment by ScottWoolven5** [comment]
If anyone else has this problem, I disabled the Home Assistant Dev skill on Alexa and re-enabled and it works.
