### ISSUE TITLE
Error adding entities for domain light with platform alexa_media

### ISSUE THREAD

**Issue by driagi** [alandtse/alexa_media_player#2188]
After updating to a new version (4.9.1) the light stopped working

![Screenshot 2024-02-13 075315](https://github.com/alandtse/alexa_media_player/assets/74871092/4116d0b0-819d-4a86-bf2b-0805b5f32696)

**System details**

- Home-assistant core:  2024.2.1
- alexa_media (version from `const.py` or HA startup): 4.9.1
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10

**Logs**
2024-02-13 07:07:55.031 INFO (MainThread) [alexapy.alexaapi] Backing off _static_request(...) for 0.6s (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests)
2024-02-13 07:07:55.760 INFO (MainThread) [alexapy.alexaapi] Backing off _static_request(...) for 1.4s (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests)
2024-02-13 07:07:58.675 ERROR (MainThread) [homeassistant.components.light] Error adding entities for domain light with platform alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1325, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1049, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1121, in state_attributes
    color_mode = self._light_internal_color_mode if _is_on else None
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 898, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/light.py", line 164, in color_mode
    ColorMode.HS_COLOR in self._attr_supported_color_modes
    ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ColorMode' has no attribute 'HS_COLOR'
2024-02-13 07:07:58.711 ERROR (MainThread) [homeassistant.components.light] Error while setting up alexa_media platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1325, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1049, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1121, in state_attributes
    color_mode = self._light_internal_color_mode if _is_on else None
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 898, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/light.py", line 164, in color_mode
    ColorMode.HS_COLOR in self._attr_supported_color_modes
    ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ColorMode' has no attribute 'HS_COLOR'

**Comment by driagi** [comment]
Excuse me
