### ISSUE TITLE
RuntimeError: Detected that custom integration 'alexa_media' calls async_write_ha_state

### ISSUE THREAD

**Issue by dpgh947** [alandtse/alexa_media_player#2256]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Received this error today, not sure what caused it, I just found it in the logs. I am not aware of anything failing. I have only just updated HA and the integration to latest levels (yesterday).

```
Logger: homeassistant
Source: helpers/frame.py:203
First occurred: 15:44:20 (1 occurrences)
Last logged: 15:44:20

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/sensor.py", line 433, in _trigger_event
    self.hass.bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1508, in async_fire
    self._hass.verify_event_loop_thread("async_fire")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'alexa_media' calls async_fire from a thread at custom_components/alexa_media/sensor.py, line 433: self.hass.bus.async_fire(. Please report it to the author of the 'alexa_media' custom integration.
```
**To Reproduce**

Cannot reproduce.

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version): 2024.5.2
- alexa_media (version from `const.py` or HA startup): 4.10.0
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : YES

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by f18m** [comment]
``hi, 
I'm having a similar issue. I'm not sure if it all started when I upgraded HA to 2024.5.2 or since I upgraded to version 4.10.0 of this integration.
Anyway my log message is:

```
2024-05-07 11:18:10.256 WARNING (MainThread) [async_upnp_client.profiles.profile] Failed (re-)subscribing to: uuid:98c672cc-d4fa-42b9-a5a8-9a831a349eca, reason: UpnpConnectionError('ClientConnectorError(ConnectionKey(host=\'192.168.1.4\', port=35297, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=-4268646588408695904), OSError(113, "Connect call failed (\'192.168.1.4\', 35297)"))', None)
2024-05-07 11:18:19.475 WARNING (MainThread) [async_upnp_client.profiles.profile] Failed (re-)subscribing to: uuid:9ee65516-e8c4-4f7d-85c8-72d2a581ac7b, reason: UpnpConnectionError('ClientConnectorError(ConnectionKey(host=\'192.168.1.4\', port=35297, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=-4268646588408695904), OSError(113, "Connect call failed (\'192.168.1.4\', 35297)"))', None)
2024-05-07 12:13:26.541 WARNING (SyncWorker_8) [homeassistant.helpers.frame] Detected that custom integration 'alexa_media' calls async_write_ha_state from a thread at custom_components/alexa_media/switch.py, line 217: self.async_write_ha_state(), please report it to the author of the 'alexa_media' custom integration
2024-05-07 12:13:26.541 WARNING (SyncWorker_24) [homeassistant.helpers.frame] Detected that custom integration 'alexa_media' calls async_write_ha_state from a thread at custom_components/alexa_media/switch.py, line 217: self.async_write_ha_state(), please report it to the author of the 'alexa_media' custom integration
2024-05-07 12:13:26.633 ERROR (SyncWorker_8) [homeassistant.util.logging] Exception in _handle_event when dispatching 'alexa_media_f**m@h*********m': ({'queue_state': {'dopplerId': {'deviceSerialNumber': 'G0922N06334600CK', 'deviceType': 'A2DS1Q2TPDJ48U'}, 'changeType': 'NEW_QUEUE', 'playBackOrder': 'NORMAL', 'loopMode': 'NORMAL', 'trackOrderChanged': False, 'destinationUserId': 'A3I6JFYIK91M8E'}},)
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/switch.py", line 217, in _handle_event
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'alexa_media' calls async_write_ha_state from a thread at custom_components/alexa_media/switch.py, line 217: self.async_write_ha_state(). Please report it to the author of the 'alexa_media' custom integration.

2024-05-07 12:13:26.634 ERROR (SyncWorker_24) [homeassistant.util.logging] Exception in _handle_event when dispatching 'alexa_media_f**m@h*********m': ({'queue_state': {'dopplerId': {'deviceSerialNumber': 'G0922N06334600CK', 'deviceType': 'A2DS1Q2TPDJ48U'}, 'changeType': 'NEW_QUEUE', 'playBackOrder': 'NORMAL', 'loopMode': 'NORMAL', 'trackOrderChanged': False, 'destinationUserId': 'A3I6JFYIK91M8E'}},)
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/switch.py", line 217, in _handle_event
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'alexa_media' calls async_write_ha_state from a thread at custom_components/alexa_media/switch.py, line 217: self.async_write_ha_state(). Please report it to the author of the 'alexa_media' custom integration.
```

Worse than that, today I discovered my HomeAssistant has filled to 100% the disk by writing this kind of messages to the log:

```
2024-05-08 09:25:53.250 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.250 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.250 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.251 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.251 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.251 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.251 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.251 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.251 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.251 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.251 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.251 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.252 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.252 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.253 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.253 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.253 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.253 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.253 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.253 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.253 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:25:53.253 WARNING (MainThread) [asyncio] SSL connection is closed
2024-05-08 09:26:06.004 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.004 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.005 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.005 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.005 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.006 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.006 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.006 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.006 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.007 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.007 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.007 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.008 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.008 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.008 WARNING (MainThread) [asyncio] socket.send() raised exception.
2024-05-08 09:26:06.008 WARNING (MainThread) [asyncio] socket.send() raised exception.
```

not sure if the the WARNING messages about SSL and socket exceptions are related to this integration though, just mentioning.

**Comment by alandtse** [comment]
Thanks for reporting.

**Comment by neil1111** [comment]
I think my issue is related. Yesterday evening, my RPI-based with SSD, HAOS system crashed. I tried rebooting several times and could not access it at all. Finally I could ping it, but still couldn't access HAOS. Eventually, about 10 min later it suddenly came up.  About 10min later the same thing happened again. Multiple reboots later, and waiting even longer, and HAOS came up again. The only CORE errors relate to alexa_media. See 3 errors below.  Then further below I pasted the Supervisor log, which while it doesn't have any errors appears to suggest (looking at the time stamps and repeated processes) that it restarted on its own a few times in the middle of the night/early morning.

I received the following error message:
Logger: homeassistant
Source: helpers/frame.py:203
First occurred: 3:00:00 AM (1 occurrences)
Last logged: 3:00:00 AM

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/sensor.py", line 433, in _trigger_event
    self.hass.bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1508, in async_fire
    self._hass.verify_event_loop_thread("async_fire")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'alexa_media' calls async_fire from a thread at custom_components/alexa_media/sensor.py, line 433: self.hass.bus.async_fire(. Please report it to the author of the 'alexa_media' custom integration.

**I bit later:**
This error originated from a custom integration.

Logger: alexapy.alexaapi
Source: custom_components/alexa_media/__init__.py:757
integration: Alexa Media Player (documentation, issues)
First occurred: May 15, 2024 at 10:41:23 PM (3 occurrences)
Last logged: 3:24:35 AM

Giving up _static_request(...) after 5 tries (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests)
Giving up _static_request(...) after 5 tries (alexapy.errors.AlexapyTooManyRequestsError)

**And a bit later:**
This error originated from a custom integration.

Logger: custom_components.alexa_media
Source: helpers/update_coordinator.py:347
integration: Alexa Media Player (documentation, issues)
First occurred: May 15, 2024 at 10:41:23 PM (3 occurrences)
Last logged: 3:24:35 AM

Error fetching alexa_media data: Error communicating with API: Too Many Requests
Error fetching alexa_media data: Error communicating with API:

**And here are the Supervisor logs**
2024-05-16 04:15:26.434 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system
2024-05-16 04:15:26.435 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system
2024-05-16 04:15:26.436 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-05-16 04:15:26.437 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-05-16 04:15:26.438 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-05-16 04:15:26.441 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-05-16 04:15:26.443 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-05-16 04:15:26.459 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-05-16 04:15:26.460 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-05-16 04:15:26.460 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-05-16 04:15:26.737 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-05-16 04:15:26.738 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-05-16 04:15:26.738 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-05-16 04:18:34.636 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-05-16 04:19:28.431 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-05-16 04:19:31.780 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/music-assistant/home-assistant-addon repository
2024-05-16 04:19:31.788 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
2024-05-16 04:19:31.796 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
2024-05-16 04:19:31.804 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
2024-05-16 04:19:31.813 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
2024-05-16 04:19:31.826 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/alexbelgium/hassio-addons repository
2024-05-16 04:19:34.771 INFO (MainThread) [supervisor.store] Loading add-ons from store: 170 all - 0 new - 0 remove
2024-05-16 04:19:34.772 INFO (MainThread) [supervisor.store] Loading add-ons from store: 170 all - 0 new - 0 remove
2024-05-16 04:39:31.227 INFO (MainThread) [supervisor.host.info] Updating local host information
2024-05-16 04:39:32.343 INFO (MainThread) [supervisor.host.services] Updating service information
2024-05-16 04:39:32.360 INFO (MainThread) [supervisor.host.network] Updating local network information
2024-05-16 04:39:32.682 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
2024-05-16 04:39:32.694 INFO (MainThread) [supervisor.host.manager] Host information reload completed
2024-05-16 04:48:40.045 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-05-16 05:15:26.740 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-05-16 05:15:26.741 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-05-16 05:15:26.814 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-05-16 05:15:26.815 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-05-16 05:15:26.816 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system
2024-05-16 05:15:26.816 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system
2024-05-16 05:15:26.817 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-05-16 05:15:26.818 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-05-16 05:15:26.819 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-05-16 05:15:26.822 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-05-16 05:15:26.824 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-05-16 05:15:26.841 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-05-16 05:15:26.843 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-05-16 05:15:26.843 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-05-16 05:15:27.123 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-05-16 05:15:27.123 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-05-16 05:15:27.124 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-05-16 05:18:45.386 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-05-16 05:46:12.305 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
2024-05-16 05:46:12.315 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
2024-05-16 05:48:50.847 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-05-16 06:15:27.126 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-05-16 06:15:27.127 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-05-16 06:15:27.207 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-05-16 06:15:27.209 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-05-16 06:15:27.209 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system
2024-05-16 06:15:27.211 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system
2024-05-16 06:15:27.212 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-05-16 06:15:27.213 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-05-16 06:15:27.219 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-05-16 06:15:27.220 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-05-16 06:15:27.221 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-05-16 06:15:27.235 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-05-16 06:15:27.236 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-05-16 06:15:27.236 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-05-16 06:15:27.509 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-05-16 06:15:27.510 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-05-16 06:15:27.510 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-05-16 06:18:56.216 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-05-16 06:19:28.528 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
2024-05-16 06:46:12.697 INFO (MainThread) [supervisor.host.info] Updating local host information
2024-05-16 06:46:13.805 INFO (MainThread) [supervisor.host.services] Updating service information
2024-05-16 06:46:13.824 INFO (MainThread) [supervisor.host.network] Updating local network information
2024-05-16 06:46:14.139 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
2024-05-16 06:46:14.152 INFO (MainThread) [supervisor.host.manager] Host information reload completed
2024-05-16 06:49:01.683 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-05-16 07:15:27.512 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
2024-05-16 07:15:27.513 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
2024-05-16 07:15:27.596 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
2024-05-16 07:15:27.598 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
2024-05-16 07:15:27.599 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system
2024-05-16 07:15:27.600 INFO (MainThread) [supervisor.resolution.checks.base] Run check for disabled_data_disk/system
2024-05-16 07:15:27.601 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
2024-05-16 07:15:27.602 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
2024-05-16 07:15:27.603 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
2024-05-16 07:15:27.606 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
2024-05-16 07:15:27.607 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
2024-05-16 07:15:27.622 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
2024-05-16 07:15:27.623 INFO (MainThread) [supervisor.resolution.check] System checks complete
2024-05-16 07:15:27.623 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
2024-05-16 07:15:27.935 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
2024-05-16 07:15:27.936 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
2024-05-16 07:15:27.936 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
2024-05-16 07:19:07.083 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
2024-05-16 07:19:34.784 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/music-assistant/home-assistant-addon repository
2024-05-16 07:19:34.792 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
2024-05-16 07:19:34.802 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
2024-05-16 07:19:34.808 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
2024-05-16 07:19:34.825 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
2024-05-16 07:19:34.833 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/alexbelgium/hassio-addons repository
2024-05-16 07:19:37.718 INFO (MainThread) [supervisor.store] Loading add-ons from store: 170 all - 0 new - 0 remove
2024-05-16 07:19:37.719 INFO (MainThread) [supervisor.store] Loading add-ons from store: 170 all - 0 new - 0 remove

Thanks for any help.

**Comment by bdraco** [comment]
If someone wants to work on this, the docs are here: 

https://developers.home-assistant.io/docs/asyncio_thread_safety#hassbusasync_fire

https://developers.home-assistant.io/docs/asyncio_thread_safety#async_write_ha_state

**Comment by Tr1n0va** [comment]
Same here i think.

Logger: homeassistant.util.logging
Quelle: util/logging.py:98
Erstmals aufgetreten: 18:51:55 (4 Vorkommnisse)
Zuletzt protokolliert: 18:52:06

Exception in _handle_event when dispatching 'alexa_media_t*m@f***********t': ({'queue_state': {'dopplerId': {'deviceSerialNumber': 'G090LF1181340N1J', 'deviceType': 'A3S5BH2HU6VAYF'}, 'changeType': 'NEW_QUEUE', 'playBackOrder': 'NORMAL', 'loopMode': 'NORMAL', 'trackOrderChanged': False, 'destinationUserId': 'A2CE33QXLYXM29'}},) Traceback (most recent call last): File "/config/custom_components/alexa_media/switch.py", line 217, in _handle_event self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state self.hass.verify_event_loop_thread("async_write_ha_state") File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'alexa_media' calls async_write_ha_state from a thread at custom_components/alexa_media/switch.py, line 217: self.async_write_ha_state(). Please report it to the author of the 'alexa_media' custom integration.

———————————————————————-

Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:190
Erstmals aufgetreten: 18:51:55 (4 Vorkommnisse)
Zuletzt protokolliert: 18:52:06

Detected that custom integration 'alexa_media' calls async_write_ha_state from a thread at custom_components/alexa_media/switch.py, line 217: self.async_write_ha_state(), please report it to the author of the 'alexa_media' custom integration
