### ISSUE TITLE
Showing that Echo is playing when tts.cloud_say is saying something

### ISSUE THREAD

**Issue by thisisbenwoo** [alandtse/alexa_media_player#2261]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I want to know which Echo is actually playing the message I send using tts.cloud_say service. 

**To Reproduce**

Using Developer Tools | Service issue the following:
```
service: tts.cloud_say
data:
  entity_id: media_player.lr
  message: Hello how are you

```

**Expected behavior**

It correctly plays the message, but nothing shows that the message is being played. The screenshot below shows that nothing changes while the message is being played.

**Screenshots**

![image](https://github.com/alandtse/alexa_media_player/assets/45885373/2a0ec5ac-1b6c-4f8a-9939-88176fde716e)

**System details**

- Home-assistant (version): 2024.5.2
- alexa_media (version from `const.py` or HA startup): 4.10.0
- alexapy (version from `pip show alexapy` or HA startup): 
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Logs**

```
2024-05-10 14:57:02.090 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration fontawesome which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.092 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.094 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.096 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration samsungtv_smart which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.097 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.099 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration fullykiosk which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.101 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.102 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration chime_tts which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.104 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration watchman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.106 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.107 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration meross_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.109 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration liveboxtvuhd which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.111 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tplink_easy_smart which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.117 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:02.119 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-10 14:57:06.986 WARNING (MainThread) [homeassistant.components.time_date.sensor] 'beat': is deprecated and will be removed in version 2024.7
2024-05-10 14:57:07.739 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.12/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

2024-05-10 14:57:08.657 ERROR (SyncWorker_2) [custom_components.liveboxtvuhd.client] HTTPConnectionPool(host='192.168.2.65', port=8080): Max retries exceeded with url: /remoteControl/cmd?operation=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a4de390>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-05-10 14:57:08.732 WARNING (MainThread) [homeassistant.helpers.entity] Entity media_player.livebox (<class 'custom_components.liveboxtvuhd.media_player.LiveboxTvUhdDevice'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|VOLUME_MUTE|PREVIOUS_TRACK|NEXT_TRACK|TURN_ON|TURN_OFF|VOLUME_STEP|SELECT_SOURCE|PLAY: 19897>, please report it to the author of the 'liveboxtvuhd' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-05-10 14:57:09.546 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://accounts.nabucasa.com/instance/resolve_dns_cname (400)
2024-05-10 14:57:09.547 ERROR (MainThread) [hass_nabucasa.remote] Can't resolve CNAME for home.example.org
2024-05-10 14:57:10.088 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from meross_cloud, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'meross_cloud' custom integration
2024-05-10 14:57:11.107 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-05-10 14:57:12.646 WARNING (MainThread) [custom_components.meross_cloud] Skip MQTT cert validation option set to: True
2024-05-10 14:57:12.691 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from fullykiosk, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'fullykiosk' custom integration
2024-05-10 14:57:12.705 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from fullykiosk, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'fullykiosk' custom integration
2024-05-10 14:57:12.765 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.chime_tts',) in /usr/src/homeassistant/homeassistant/loader.py, line 1041: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop
2024-05-10 14:57:12.782 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/asyncio/base_events.py:1973: RuntimeWarning: coroutine 'ChimeTTSQueueManager.queue_processor' was never awaited
  handle = self._ready.popleft()

2024-05-10 14:57:12.886 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'browser_mod' accesses hass.helpers.storage. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from storage directly at custom_components/browser_mod/store.py, line 94: self.store = hass.helpers.storage.Store(STORAGE_VERSION, STORAGE_KEY), please report it to the author of the 'browser_mod' custom integration
2024-05-10 14:57:12.989 ERROR (MainThread) [meross_iot.http_api] Login API redirected to different region: https://iotx-us.meross.com. Login will be re-attempted
2024-05-10 14:57:14.597 WARNING (MainThread) [custom_components.meross_cloud] Returned/Stored DOMAIN within existing credentials is <https://iotx-us.meross.com>. Patching the stored credentials with the correct value right away.
2024-05-10 14:57:16.022 WARNING (MainThread) [custom_components.meross_cloud] 
===============================
Meross Cloud Custom component
Developed by Alberto Geniola
Low level library version: 0.4.7.0
-------------------------------
This custom component is under development and not yet ready for production use.
In case of errors/misbehave, please report it here: 
https://github.com/albertogeniola/meross-homeassistant/issues

If you like this extension and you want to support it, please consider donating.
-------------------------------
List of devices reported by HTTP API:
- Datacenter Master (mss310) - OnlineStatus.ONLINE
===============================
2024-05-10 14:57:17.840 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'adaptive_lighting' calls `async_listen` with run_immediately, which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/adaptive_lighting/switch.py, line 1665: self.hass.bus.async_listen(, please create a bug report at https://github.com/basnijholt/adaptive-lighting/issues
2024-05-10 14:57:17.853 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'adaptive_lighting' calls `async_listen` with run_immediately, which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/adaptive_lighting/switch.py, line 1670: self.hass.bus.async_listen(, please create a bug report at https://github.com/basnijholt/adaptive-lighting/issues
2024-05-10 14:57:17.875 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'adaptive_lighting' calls `async_listen_once` with run_immediately, which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/adaptive_lighting/switch.py, line 958: self.hass.bus.async_listen_once(, please create a bug report at https://github.com/basnijholt/adaptive-lighting/issues
2024-05-10 14:57:18.206 WARNING (MainThread) [meross_iot.manager] Found a new device Datacenter Master (mss310, HW 8.0.0, FW 6.3.23, class: mss310:8.0.0:6.3.23) that has become online while we were offline.
2024-05-10 14:57:18.818 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.dishwasher (<class 'homeassistant.components.utility_meter.sensor.UtilityMeterSensor'>) is using state class 'total' which is impossible considering device class ('power') it is using; expected None or one of 'measurement'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+utility_meter%22
2024-05-10 14:57:18.849 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.fullykiosk.light.FullyLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 1> and color modes, please create a bug report at https://github.com/cgarwood/homeassistant-fullykiosk/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-05-10 14:57:18.850 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.fullykiosk.light.FullyLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/cgarwood/homeassistant-fullykiosk/issues
2024-05-10 14:57:18.863 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.fullykiosk.media_player.FullyMediaPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.VOLUME_SET|PLAY_MEDIA: 516>, please create a bug report at https://github.com/cgarwood/homeassistant-fullykiosk/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-05-10 14:57:18.885 WARNING (ImportExecutor_0) [homeassistant.const] DATA_MEGABYTES was used from fullykiosk, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfInformation.MEGABYTES instead, please report it to the author of the 'fullykiosk' custom integration
2024-05-10 14:57:22.334 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from meross_cloud, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'meross_cloud' custom integration
2024-05-10 14:57:22.354 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from meross_cloud, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'meross_cloud' custom integration
2024-05-10 14:57:22.393 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from meross_cloud, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'meross_cloud' custom integration
2024-05-10 14:57:22.411 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from meross_cloud, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'meross_cloud' custom integration
2024-05-10 14:57:22.436 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from meross_cloud, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'meross_cloud' custom integration
2024-05-10 14:57:22.458 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from meross_cloud, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'meross_cloud' custom integration
2024-05-10 14:57:22.682 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from auto_backup, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'auto_backup' custom integration
2024-05-10 14:57:22.695 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] ServiceCallType was used from auto_backup, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'auto_backup' custom integration
2024-05-10 14:57:22.862 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from auto_backup, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'auto_backup' custom integration
2024-05-10 14:57:22.878 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] EventType was used from auto_backup, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.Event instead, please report it to the author of the 'auto_backup' custom integration
2024-05-10 14:57:31.193 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states('sensor.utilities_hourly_power_usage_riemann_datacenter') * states('input_number._kwh_price') }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 585, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2600, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
TypeError: can't multiply sequence by non-int of type 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 713, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 587, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: can't multiply sequence by non-int of type 'str'
2024-05-10 14:57:31.200 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('TypeError: can't multiply sequence by non-int of type 'str'') while processing template 'Template<template=({{ states('sensor.utilities_hourly_power_usage_riemann_datacenter') * states('input_number._kwh_price') }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.hourly_cost_datacenter'
2024-05-10 14:57:31.262 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-05-10 14:57:31.818 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Warning: Smoke and/or CO levels high' trigger: In 'numeric_state' condition: entity binary_sensor.detecteur_de_fumee_et_monoxyde_de_carbon_smoke state 'off' cannot be processed as a number
2024-05-10 14:58:10.531 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547259488064] Error handling message: extra keys not allowed @ data['sequence'][0]['options']. Got {'type': 'DeniseNeural'} (invalid_format) Joe Citizen from 192.168.2.201 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36)
2024-05-10 14:58:13.433 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547259488064] Error handling message: extra keys not allowed @ data['sequence'][0]['options']. Got {'type': 'DeniseNeural'} (invalid_format) Joe Citizen from 192.168.2.201 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36)
2024-05-10 15:00:32.822 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'adaptive_lighting' accesses hass.helpers.entity_component. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from entity_component directly at custom_components/adaptive_lighting/switch.py, line 2471: await self.hass.helpers.entity_component.async_update_entity(light), please create a bug report at https://github.com/basnijholt/adaptive-lighting/issues
2024-05-10 15:25:58.684 DEBUG (MainThread) [custom_components.alexa_media.media_player] b**o@o*******r: <entity media_player.lr=standby>:Playing https://home.example.org/local/alexa_tts/65769f985d298f9ea20a8353e3e3835ccfdf27b6_en-au_6e8b81ac47_cloud_output.mp3
2024-05-10 15:26:00.186 DEBUG (MainThread) [alexapy.alexaapi] b**o@o*******r: Creating sequence for 1 items
2024-05-10 15:26:00.187 DEBUG (MainThread) [alexapy.alexaapi] b**o@o*******r: Running behavior with data: {"behaviorId": "PREVIEW", "sequenceJson": "{\"@type\": \"com.amazon.alexa.behaviors.model.Sequence\", \"startNode\": {\"@type\": \"com.amazon.alexa.behaviors.model.SerialNode\", \"nodesToExecute\": [{\"@type\": \"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\", \"type\": \"Alexa.Speak\", \"operationPayload\": {\"deviceType\": \"A30YDR2MK8HMRV\", \"deviceSerialNumber\": \"XXXXXXXXXXXXXX\", \"locale\": \"en-us\", \"customerId\": \"YYYYYYYYYYYYYYYY\", \"textToSpeak\": \"<audio src='https://home.example.org/local/alexa_tts/65769f985d298f9ea20a8353e3e3835ccfdf27b6_en-au_6e8b81ac47_cloud_output.mp3' />\", \"target\": {\"customerId\": \"YYYYYYYYYYYYYYYY\", \"devices\": [{\"deviceSerialNumber\": \"XXXXXXXXXXXXXX\", \"deviceTypeId\": \"A30YDR2MK8HMRV\"}]}, \"skillId\": \"amzn1.ask.1p.saysomething\"}}]}}", "status": "ENABLED"}
2024-05-10 15:26:00.187 DEBUG (MainThread) [alexapy.alexaapi] b**o@o*******r: Trying post: https://alexa.amazon.fr/api/behaviors/preview : with uri: /api/behaviors/preview data {'behaviorId': 'PREVIEW', 'sequenceJson': '{"@type": "com.amazon.alexa.behaviors.model.Sequence", "startNode": {"@type": "com.amazon.alexa.behaviors.model.SerialNode", "nodesToExecute": [{"@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode", "type": "Alexa.Speak", "operationPayload": {"deviceType": "A30YDR2MK8HMRV", "deviceSerialNumber": "XXXXXXXXXXXXXX", "locale": "en-us", "customerId": "YYYYYYYYYYYYYYYY", "textToSpeak": "<audio src=\'https://home.example.org/local/alexa_tts/65769f985d298f9ea20a8353e3e3835ccfdf27b6_en-au_6e8b81ac47_cloud_output.mp3\' />", "target": {"customerId": "YYYYYYYYYYYYYYYY", "devices": [{"deviceSerialNumber": "XXXXXXXXXXXXXX", "deviceTypeId": "A30YDR2MK8HMRV"}]}, "skillId": "amzn1.ask.1p.saysomething"}}]}}', 'status': 'ENABLED'} query None
2024-05-10 15:26:00.347 DEBUG (MainThread) [alexapy.alexaapi] b**o@o*******r: POST: https://alexa.amazon.fr/api/behaviors/preview returned 200:OK:application/octet-stream

```

**Additional context**

I am trying a number of different TTS methods including:
```
tts.cloud_say
tts.google_translate_say
tts.speak
notify.alexa_media_[device]

```
In each case, I'd like to see and monitor which device is actually broadcasting the message, so I can figure out the impact of TTS against other media that is being played, and generally get some more info about how this is all working.

Thanks

**Comment by danielbrunt57** [comment]
What you are requesting is not possible.  Alexa Media Player only sends to Amazon Cloud and the only time the cloud sends info to HA is after an `alexa_media.update_last_called`.  The integration periodically does this automatically but can only do it occasionally to prevent Amazon from shutting it down due to excessive calls.  Real time automatic updating of Alexa Media devices in HA is not something Amazon supports or even wants to support.

**Comment by thisisbenwoo** [comment]
Thank you for your answer. If it is not possible, it is not possible!
