### ISSUE TITLE
Alexa Media Blocking Call stops Home Assistant from starting

### ISSUE THREAD

**Issue by MrSolo570** [alandtse/alexa_media_player#2277]
**Describe the bug**

After updating Home Assistant the supervisor is starting but the home Assistant container keeps reporting a blocking error (see logs) and after that fails with

**To Reproduce**

Restart the Home Assistant Container or Supervisor Container

**Expected behavior**

Home Assistant should boot and by that start the Alexa Media Addon

**Screenshots**

none

**System details**
- Home-assistant (version): 2024.6.0
- alexa_media (version from `const.py` or HA startup): IDK how to provide that.
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled] yes but i dont think thats causing the issue here

**Logs**
[33m2024-06-06 13:34:49.348 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/sensor.py, line 450: timezone = pytz.timezone( (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/alandtse/alexa_media_player/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2055, in async_forward_entry_setup
    return await self._async_forward_entry_setup(entry, domain, True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2081, in _async_forward_entry_setup
    await entry.async_setup(self.hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 196, in async_setup_entry
    return await self._platforms[key].async_setup_entry(config_entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 333, in async_setup_entry
    return await self._async_setup_platform(async_create_setup_awaitable)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 363, in _async_setup_platform
    awaitable = create_eager_task(awaitable, loop=hass.loop)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/config/custom_components/alexa_media/sensor.py", line 162, in async_setup_entry
    return await async_setup_platform(
  File "/config/custom_components/alexa_media/sensor.py", line 151, in async_setup_platform
    return await add_devices(
  File "/config/custom_components/alexa_media/helpers.py", line 53, in add_devices
    add_devices_callback(devices, False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 515, in _async_schedule_add_entities_for_entry
    task = self.config_entry.async_create_task(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1134, in async_create_task
    task = hass.async_create_task_internal(
  File "/usr/src/homeassistant/homeassistant/core.py", line 828, in async_create_task_internal
    task = create_eager_task(target, name=name, loop=self.loop)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 649, in async_add_entities
    await add_func(coros, entities, timeout)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 600, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 914, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1354, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/alexa_media/sensor.py", line 541, in async_added_to_hass
    self._process_raw_notifications()
  File "/config/custom_components/alexa_media/sensor.py", line 382, in _process_raw_notifications
    list(map(self._fix_alarm_date_time, self._n_dict.items()))
  File "/config/custom_components/alexa_media/sensor.py", line 450, in _fix_alarm_date_time
    timezone = pytz.timezone(

...

and then:

[33m2024-06-06 13:34:50.121 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/sensor.py, line 450: timezone = pytz.timezone( (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/alandtse/alexa_media_player/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homea[11:35:06] INFO: [32mHome Assistant Core finish process exit code 256[0m
[11:35:06] INFO: [32mHome Assistant Core finish process received signal 7[0m
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Additional context**

**Comment by meluvalli** [comment]
Same issue.
```
2024-06-06 08:42:55.497 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/sensor.py, line 450: timezone = pytz.timezone( (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/alandtse/alexa_media_player/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2055, in async_forward_entry_setup
    return await self._async_forward_entry_setup(entry, domain, True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2081, in _async_forward_entry_setup
    await entry.async_setup(self.hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 196, in async_setup_entry
    return await self._platforms[key].async_setup_entry(config_entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 333, in async_setup_entry
    return await self._async_setup_platform(async_create_setup_awaitable)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 363, in _async_setup_platform
    awaitable = create_eager_task(awaitable, loop=hass.loop)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/config/custom_components/alexa_media/sensor.py", line 162, in async_setup_entry
    return await async_setup_platform(
  File "/config/custom_components/alexa_media/sensor.py", line 151, in async_setup_platform
    return await add_devices(
  File "/config/custom_components/alexa_media/helpers.py", line 53, in add_devices
    add_devices_callback(devices, False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 515, in _async_schedule_add_entities_for_entry
    task = self.config_entry.async_create_task(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1134, in async_create_task
    task = hass.async_create_task_internal(
  File "/usr/src/homeassistant/homeassistant/core.py", line 828, in async_create_task_internal
    task = create_eager_task(target, name=name, loop=self.loop)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 649, in async_add_entities
    await add_func(coros, entities, timeout)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 600, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 914, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1354, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/alexa_media/sensor.py", line 541, in async_added_to_hass
    self._process_raw_notifications()
  File "/config/custom_components/alexa_media/sensor.py", line 382, in _process_raw_notifications
    list(map(self._fix_alarm_date_time, self._n_dict.items()))
  File "/config/custom_components/alexa_media/sensor.py", line 450, in _fix_alarm_date_time
    timezone = pytz.timezone(

```

**Comment by Harway2007** [comment]
the complete Alexa 4.10.1 isn*t work since 14 days ...
how know*s a solution ?

**Comment by downtownsj1973** [comment]
Seeing this as well

`Detected blocking call to open inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/sensor.py, line 450: timezone = pytz.timezone( (offender: /srv/homeassistant/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/alandtse/alexa_media_player/issues Traceback (most recent call last): File "/srv/homeassistant/bin/hass", line 8, in <module> sys.exit(main()) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 651, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 618, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1951, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 84, in _run self._context.run(self._callback, *self._args) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 2055, in async_forward_entry_setup return await self._async_forward_entry_setup(entry, domain, True) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 2081, in _async_forward_entry_setup await entry.async_setup(self.hass, integration=integration) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/components/sensor/__init__.py", line 134, in async_setup_entry return await component.async_setup_entry(entry) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_component.py", line 196, in async_setup_entry return await self._platforms[key].async_setup_entry(config_entry) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 333, in async_setup_entry return await self._async_setup_platform(async_create_setup_awaitable) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 363, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/home/homeassistant/.homeassistant/custom_components/alexa_media/sensor.py", line 162, in async_setup_entry return await async_setup_platform( File "/home/homeassistant/.homeassistant/custom_components/alexa_media/sensor.py", line 151, in async_setup_platform return await add_devices( File "/home/homeassistant/.homeassistant/custom_components/alexa_media/helpers.py", line 53, in add_devices add_devices_callback(devices, False) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 515, in _async_schedule_add_entities_for_entry task = self.config_entry.async_create_task( File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 1134, in async_create_task task = hass.async_create_task_internal( File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/core.py", line 828, in async_create_task_internal task = create_eager_task(target, name=name, loop=self.loop) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 649, in async_add_entities await add_func(coros, entities, timeout) File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 600, in _async_add_entities await coro File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 914, in _async_add_entity await entity.add_to_platform_finish() File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1354, in add_to_platform_finish await self.async_added_to_hass() File "/home/homeassistant/.homeassistant/custom_components/alexa_media/sensor.py", line 541, in async_added_to_hass self._process_raw_notifications() File "/home/homeassistant/.homeassistant/custom_components/alexa_media/sensor.py", line 382, in _process_raw_notifications list(map(self._fix_alarm_date_time, self._n_dict.items())) File "/home/homeassistant/.homeassistant/custom_components/alexa_media/sensor.py", line 450, in _fix_alarm_date_time timezone = pytz.timezone(`

**Comment by MrSolo570** [comment]
I know this wont help but I was using home assistant supervised.
Now I set up a new sd card with home assistant operating system and used a fresh backup. This worked like a charm. After that i first updated alexa media to the latest version and then updated home assistant to 2024.06. Everything works fine. I cannot say if this error is caused by supervised installation method or the combination of home assistant 2024.06 and alexa 4.10.1...

**Comment by danielgoepp** [comment]
Same issue, thought HA will load for me, just Alexa is completely broken. Just that error message around 600 times on load. I did see additional errors in the logs too

```
2024-06-07 03:58:24.225 INFO (MainThread) [homeassistant.components.switch] Setting up alexa_media.switch
2024-06-07 03:58:24.225 ERROR (MainThread) [homeassistant.helpers.entity_platform] alexa_media raises exception ConfigEntryNotReady in forwarded platform switch; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups
2024-06-07 03:58:24.225 INFO (MainThread) [homeassistant.components.sensor] Setting up alexa_media.sensor
2024-06-07 03:58:24.225 ERROR (MainThread) [homeassistant.helpers.entity_platform] alexa_media raises exception ConfigEntryNotReady in forwarded platform sensor; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups
2024-06-07 03:58:24.226 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alexa_media.alarm_control_panel
2024-06-07 03:58:24.226 ERROR (MainThread) [homeassistant.helpers.entity_platform] alexa_media raises exception ConfigEntryNotReady in forwarded platform alarm_control_panel; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups
2024-06-07 03:58:24.226 INFO (MainThread) [homeassistant.components.light] Setting up alexa_media.light
2024-06-07 03:58:24.226 ERROR (MainThread) [homeassistant.helpers.entity_platform] alexa_media raises exception ConfigEntryNotReady in forwarded platform light; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups
2024-06-07 03:58:24.226 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up alexa_media.binary_sensor
2024-06-07 03:58:24.226 ERROR (MainThread) [homeassistant.helpers.entity_platform] alexa_media raises exception ConfigEntryNotReady in forwarded platform binary_sensor; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups
```

**Comment by javiges** [comment]
Yo también con el mismo error, 2024-06-07 10:35:21.738 ADVERTENCIA (MainThread) [homeassistant.util.loop] Se detectó una llamada de bloqueo para abrir dentro del bucle de eventos mediante la integración personalizada 'alexa_media' en custom_components/alexa_media/sensor. py, línea 450: timezone = pytz.timezone( (delincuente: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, línea 108: return open(filename, 'rb')), por favor cree un informe de error en https://github.com/alandtse/alexa_media_player/issues
Rastreo (llamadas recientes más última):
 Archivo "<frozen runpy>", línea 198, en _run_module_as_main
 Archivo "<frozen runpy>", línea 88, en _run_code
 Archivo "/usr/src/homeassistant/homeassistant/__main__.py", línea 223, en <módulo>
 sys.salir(principal())
 Archivo "/usr/src/homeassistant/homeassistant/__main__.py", línea 209, en principal
 código_salida = corredor.run(runtime_conf)
 Archivo "/usr/src/homeassistant/homeassistant/runner.py", línea 190, en ejecución
 retorno loop.run_until_complete(setup_and_run_hass(runtime_config))
 Archivo "/usr/local/lib/python3.12/asyncio/base_events.py", línea 672, en run_until_complete
 self.run_forever()
 Archivo "/usr/local/lib/python3.12/asyncio/base_events.py", línea 639, en run_forever
 self._run_once()
 Archivo "/usr/local/lib/python3.12/asyncio/base_events.py", línea 1988, en _run_once
 manejar._run()
 Archivo "/usr/local/lib/python3.12/asyncio/events.py", línea 88, en _run
 self._context.run(self._callback, *self._args)
 Archivo "/usr/src/homeassistant/homeassistant/config_entries.py", línea 2055, en async_forward_entry_setup
 return await self._async_forward_entry_setup(entrada, dominio, Verdadero)
 Archivo "/usr/src/homeassistant/homeassistant/config_entries.py", línea 2081, en _async_forward_entry_setup
 espera entrada.async_setup(self.hass, integración=integración)
 Archivo "/usr/src/homeassistant/homeassistant/config_entries.py", línea 594, en async_setup
 resultado = esperar componente.async_setup_entry(hass, self)
 Archivo "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", línea 134, en async_setup_entry
 volver a esperar componente.async_setup_entry(entrada)
 Archivo "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", línea 196, en async_setup_entry
 regresar espera self._platforms[key].async_setup_entry(config_entry)
 Archivo "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", línea 333, en async_setup_entry
 volver en espera de self._async_setup_platform(async_create_setup_awaitable)
 Archivo "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", línea 363, en _async_setup_platform
 aguardable = create_eager_task(aguardable, bucle=hass.loop)
 Archivo "/usr/src/homeassistant/homeassistant/util/async_.py", línea 37, en create_eager_task
 devolver Tarea (coro, bucle = bucle, nombre = nombre, ansioso_inicio = Verdadero)
 Archivo "/config/custom_components/alexa_media/sensor.py", línea 162, en async_setup_entry
 volver aguardar async_setup_platform(
 Archivo "/config/custom_components/alexa_media/sensor.py", línea 151, en async_setup_platform
 volver aguardar add_devices(
 Archivo "/config/custom_components/alexa_media/helpers.py", línea 53, en add_devices
 add_devices_callback(dispositivos, Falso)
 Archivo "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", línea 515, en _async_schedule_add_entities_for_entry
 tarea = self.config_entry.async_create_task(
 Archivo "/usr/src/homeassistant/homeassistant/config_entries.py", línea 1134, en async_create_task
 tarea = hass.async_create_task_internal(
 Archivo "/usr/src/homeassistant/homeassistant/core.py", línea 828, en async_create_task_internal
 tarea = create_eager_task(objetivo, nombre=nombre, bucle=self.loop)
 Archivo "/usr/src/homeassistant/homeassistant/util/async_.py", línea 37, en create_eager_task
 devolver Tarea (coro, bucle = bucle, nombre = nombre, ansioso_inicio = Verdadero)
 Archivo "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", línea 649, en async_add_entities
 await add_func(coros, entidades, tiempo de espera)
 Archivo "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", línea 600, en _async_add_entities
 espera coro
 Archivo "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", línea 914, en _async_add_entity
 espera entidad.add_to_platform_finish()
 Archivo "/usr/src/homeassistant/homeassistant/helpers/entity.py", línea 1354, en add_to_platform_finish
 espera self.async_added_to_hass()
 Archivo "/config/custom_components/alexa_media/sensor.py", línea 541, en async_added_to_hass
 self._process_raw_notificaciones()
 Archivo "/config/custom_components/alexa_media/sensor.py", línea 382, ​​en _process_raw_notifications
 lista(mapa(self._fix_alarm_date_time, self._n_dict.items()))
 Archivo "/config/custom_components/alexa_media/sensor.py", línea 450, en _fix_alarm_date_time
 zona horaria = pytz.zona horaria (
, haber si alguien puede ayudarnos, lo bueno es que me funcionan los alexa, gracias.

**Comment by javiges** [comment]
I believe that the error in Home Assistant indicates that there is a blocking call within the event loop, which is not allowed in asynchronous programming. This happens in the custom integration 'alexa_media' when you try to open a file with pytz.timezone in a function that should be non-blocking, but I don't know how to fix it and that means that as soon as home assistant starts the log suddenly goes up to 2.80mb

**Comment by javiges** [comment]
can we do something?  or will there be an update?  Thanks for the work, you are to be admired.

**Comment by javiges** [comment]
I just saw the update on hacs, thanks, you are geniuses

**Comment by martin3000** [comment]
> I believe that the error in Home Assistant indicates that there is a blocking call within the event loop, which is not allowed in asynchronous programming. This happens in the custom integration 'alexa_media' when you try to open a file with pytz.timezone in a function that should be non-blocking, but I don't know how to fix it and that means that as soon as home assistant starts the log suddenly goes up to 2.80mb

Normally you have to import tzdata so that the calling modules doesn't do it, and then you define a constant with the time zone so that in the async calls you don't have to convert the time zone with every call.
