### ISSUE TITLE
Integration broken after upgrading HA Core to 2024.7.0

### ISSUE THREAD

**Issue by rodrigogbs** [alandtse/alexa_media_player#2300]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After upgrading HA Core to 2024.7.0 the devices are not updated anymore, and shows unavailable.

**To Reproduce**

Update HA Core to 2024.7.0 and look for the alexa devices status.

1. Go to Entities
2. Look for Alexa Media Player entities
3. See the status of them - unavailable

**Expected behavior**

After updating the HA core, everything must work fine, as in the later version.

**Screenshots**

N/A

**System details**

- Home-assistant (version): 2024.7.0
- alexa_media (version from `const.py` or HA startup): 4.10.2
- alexapy (version from `pip show alexapy` or HA startup): 4.10.2
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). N

**Logs**
```
Logger: alexapy.helpers
Source: runner.py:190
First occurred: 3:28:56 PM (8 occurrences)
Last logged: 3:32:22 PM

alexaapi.get_devices((<alexapy.alexalogin.AlexaLogin object at 0x7ff33333b3e0>,), {}): A connection error occurred: An exception of type KeyError occurred. Arguments: ('account e-mail',)
```

**Additional context**

N/A

**Comment by kyleb822** [comment]
Same issue for me, everything unavailable after upgrading HA Core to 2024.7.0

**Comment by Scope666** [comment]
More logs:

```
-------------------------------------------------------------------
alexa_media
Version: 4.10.2
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/alandtse/alexa_media_player/issues
-------------------------------------------------------------------

2024-07-03 14:46:30.988 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==1.27.10
2024-07-03 14:46:32.212 WARNING (MainThread) [alexapy.helpers] alexaapi.get_devices((<alexapy.alexalogin.AlexaLogin object at 0x14624b8c41a0>,), {}): A connection error occurred: An exception of type KeyError occurred. Arguments:
('none@gmail.com',)
2024-07-03 14:46:32.212 ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API: 
2024-07-03 14:47:18.353 WARNING (MainThread) [alexapy.helpers] alexaapi.get_devices((<alexapy.alexalogin.AlexaLogin object at 0x14624b8c41a0>,), {}): A connection error occurred: An exception of type KeyError occurred. Arguments:
('none@gmail.com',)
```

**Comment by bakernigel** [comment]
Same issue here

**Comment by bdlarmor** [comment]
+1 Just updated to core 2024.07 and the integration stopped working.

**Comment by totallydifferent** [comment]
This is back up and running for me. I restarted HA although not sure that was required.

**Comment by bakernigel** [comment]
Came back up around 12:30 PDT. No HA restart required. I suspect an Amazon issue that happened coincidently when I did the upgrade to 2024.7.0

**Comment by thejeffreystone** [comment]
Mine stop working on update as well. Log reports
`ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API: Too Many Requests`

Going to try and disable for a few minutes and re-enable and see if that fixes it. I dont see any other errors.

**Comment by thejeffreystone** [comment]
Meh, back up. So weird. I'm good now.

**Comment by rodrigogbs** [comment]
New information in logs:

```
Logger: homeassistant.helpers.frame Source: helpers/frame.py:184 First occurred: 6:34:51 PM (17 occurrences) Last logged: 7:51:08 PM
* Detected that custom integration 'alexa_media' calls async_forward_entry_setup for integration, alexa_media with title: account@gmail.com - amazon.com and entry_id: ID, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/alexa_media/__init__.py, line 625: config_entry.async_create_task(, please create a bug report at https://github.com/alandtse/alexa_media_player/issues
* Detected that custom integration 'alexa_media' calls async_forward_entry_setup for integration, alexa_media with title: account@gmail.com - amazon.com and entry_id: ID, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/alexa_media/media_player.py, line 188: config_entry.async_create_task(, please create a bug report at https://github.com/alandtse/alexa_media_player/issues
* Detected that custom integration 'average' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/average/sensor.py, line 246: async_track_state_change(, please create a bug report at https://github.com/Limych/ha-average/issues
* Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
* Detected that custom integration 'alexa_media' accesses hass.components.persistent_notification. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from persistent_notification directly at custom_components/alexa_media/__init__.py, line 1291: hass.components.persistent_notification.async_dismiss(, please create a bug report at https://github.com/alandtse/alexa_media_player/issues
```


```
Logger: homeassistant.config_entries
Source: config_entries.py:801
First occurred: 7:51:08 PM (2 occurrences)
Last logged: 7:51:37 PM

Error unloading entry account@gmail.com - amazon.com for notify
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 801, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 135, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by rodrigogbs** [comment]
After some hours everything started working again, as some guys said above, so, I believe that it really was API Amazon issues.
