### ISSUE TITLE
Unable to load alexa_media_player on HA 2024.7 :  Setup failed for custom integration 'alexa_media': Unable to import component: Exception importing custom_components.alexa_media

### ISSUE THREAD

**Issue by st3v3nFr** [alandtse/alexa_media_player#2309]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

On loading HA after updating to HA 2024.7.x, the plugin does not load.
Notification Error given : 

Setup failed for custom integration 'alexa_media': Unable to import component: Exception importing custom_components.alexa_media

Unexpected exception importing component custom_components.alexa_media

Detected blocking call to listdir with args ('/config/deps/lib/python3.12/site-packages',) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 16: from alexapy import ( (offender: /usr/local/lib/python3.12/site-packages/importlib_metadata/__init__.py, line 727: return os.listdir(self.root or '.')), please create a bug report at https://github.com/alandtse/alexa_media_player/issues For developers,

Detected blocking call to import_module with args ('custom_components.alexa_media',) in /usr/src/homeassistant/homeassistant/loader.py, line 1067: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers

**To Reproduce**

Upgrade  your HA installation fron 2024.6.x to 2024.7.x

**System details**

- Home-assistant (version): 2024.7.2
- alexa_media (version from `const.py` or HA startup):  v4.10.3
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) : Yes

**Logs**
Détails du journal (ERREUR)
Enregistreur: homeassistant.setup
Source: setup.py:322
S'est produit pour la première fois: 19:12:56 (1 occurrences)
Dernier enregistrement: 19:12:56

Setup failed for custom integration 'alexa_media': Unable to import component: Exception importing custom_components.alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.12/site-packages/alexapy/__init__.py", line 41, in <module>
    __maintainer__ = metadata["maintainer"]
                     ~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/importlib_metadata/_adapters.py", line 54, in __getitem__
    raise KeyError(item)
KeyError: 'maintainer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.alexa_media

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.12/site-packages/alexapy/__init__.py", line 41, in <module>
    __maintainer__ = metadata["maintainer"]
                     ~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/importlib_metadata/_adapters.py", line 54, in __getitem__
    raise KeyError(item)
KeyError: 'maintainer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 322, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.alexa_media



Détails du journal (ERREUR)
Enregistreur: homeassistant.loader
Source: loader.py:1067
S'est produit pour la première fois: 19:12:56 (2 occurrences)
Dernier enregistrement: 19:12:56

Unexpected exception importing component custom_components.alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.12/site-packages/alexapy/__init__.py", line 41, in <module>
    __maintainer__ = metadata["maintainer"]
                     ~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/importlib_metadata/_adapters.py", line 54, in __getitem__
    raise KeyError(item)
KeyError: 'maintainer'


Détails du journal (AVERTISSEMENT)
Enregistreur: homeassistant.util.loop
Source: util/loop.py:136
S'est produit pour la première fois: 19:12:56 (1 occurrences)
Dernier enregistrement: 19:12:56

Detected blocking call to listdir with args ('/config/deps/lib/python3.12/site-packages',) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 16: from alexapy import ( (offender: /usr/local/lib/python3.12/site-packages/importlib_metadata/__init__.py, line 727: return os.listdir(self.root or '.')), please create a bug report at https://github.com/alandtse/alexa_media_player/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 322, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path) File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 995, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/config/custom_components/alexa_media/__init__.py", line 16, in <module> from alexapy import (

Détails du journal (AVERTISSEMENT)
Enregistreur: homeassistant.util.loop
Source: util/loop.py:77
S'est produit pour la première fois: 19:12:56 (1 occurrences)
Dernier enregistrement: 19:12:56

Detected blocking call to import_module with args ('custom_components.alexa_media',) in /usr/src/homeassistant/homeassistant/loader.py, line 1067: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 322, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)

**Comment by mk-maddin** [comment]
I have the same issue with:

Core: 			2024.7.2
Supervisor: 		2024.06.2
Operating System: 	12.4
Frontend: 		20240710.0

Never the less this looks like a duplicate to: https://github.com/alandtse/alexa_media_player/issues/2293

**Comment by Gallach** [comment]
I'm also facing the same issue with same versions:

Home-assistant (version): 2024.7.2
alexa_media (version): v4.10.3

**Comment by danielbrunt57** [comment]
Try redownloading the package in HACS...

**Comment by st3v3nFr** [comment]
> Try redownloading the package in HACS...

Already try it, no change at all still can`t load

**Comment by lvcabral** [comment]
I had the same trouble with 4.10.3 so I rolled back to 4.10.2 and it is working again.

**Comment by mk-maddin** [comment]
> I had the same trouble with 4.10.3 so I rolled back to 4.10.2 and it is working again.

Unfortunately does not solve the issue for me :/
Removed 4.10.3
Installed 4.10.2 -> Same issue
Updated again to 4.10.3 -> Same issue.

Did you just rollback the alexa_media_player component or restore from a full backup?
As of my research it seems more related to the importlib_metadata and alexapy pypi package ...

**Comment by st3v3nFr** [comment]
Same here, whatever is the version, i'm stuck with the issue.
As it seems to work for certain people and not for US , we may share common situation that can explain the source of the issue.

My HA runs within a Virtual machine in Proxmox.
Is that the case for you ?

**Comment by mk-maddin** [comment]
> My HA runs within a Virtual machine in Proxmox. Is that the case for you ?

No - I am running Home Assistant OS on X86 machine.
I was able to work around the issue by "pinning" importlib-metadata to 6.8.0 version (the one mentioned in requirements.txt in AlexaPy package), using the requirements in manifest.json of alexa_media_player package:

` "requirements": ["alexapy==1.27.10", "packaging>=20.3", "wrapt>=1.14.0", "importlib-metadata==6.8.0"],`

**Comment by st3v3nFr** [comment]
DId you just add  ' , "importlib-metadata==6.8.0" ' this ?
I tried without no luck

**Comment by mk-maddin** [comment]
Yes but that's only a workaround.
It is just a matter of time until when any other integration requires importlib-metadata in a higher version and thus cause version conflict and 6.8.0 is already one year old (but newer version did not seem to work for me)

**Comment by danielbrunt57** [comment]
Please try adding custom repository [https://github.com/danielbrunt57/alexa_media_player](https://github.com/danielbrunt57/alexa_media_player), install latest version (4.10.3.1) and report results.

**Comment by marcodefraia** [comment]
It works!

**Comment by casa3c** [comment]
Does not work, I got this error message:  “ No se pudo cargar el flujo de configuración: {"message":"Invalid handler specified"}”

**Comment by casa3c** [comment]
> Does not work, I got this error message: “ No se pudo cargar el flujo de configuración: {"message":"Invalid handler specified"}”

I correct my previous comment, after reloaded it worked¡!!!
Thanks you, made my day!
Gracias

**Comment by st3v3nFr** [comment]
LAst Alexa update fix all issues !
th you !!

**Comment by danielbrunt57** [comment]
AMP v4.11.0 has been released but does not include the change I made in my fork.
I will be removing my 4.10.3.x, forking the new 4.11.0 and creating a new release with `importlib-metadata==6.8.0` and submitting a new PR...

**Comment by hmdibella** [comment]
It's not working for me... just updated to 4.11.0 and still with the same issue.

**Comment by danielbrunt57** [comment]
I just posted a lengthy reply at https://github.com/alandtse/alexa_media_player/issues/2293#issuecomment-2237349747
Can you try those steps?

**Comment by dasc19** [comment]
It's nor working for me neither version 4.11.0..I already fo
<img width="1351" alt="alexa" src="https://github.com/user-attachments/assets/7e8a3629-7fe3-4dc1-8f09-6777de12beb1">
llow daniel's procedure wo success .Lod attached file

**Comment by danielbrunt57** [comment]
v4.11.4??

**Comment by danielbrunt57** [comment]
Also, what is the first alex_media error after restart?

**Comment by danielbrunt57** [comment]
I just updated mine to 4.11.4 and it loaded fine.

**Comment by st3v3nFr** [comment]
Here is all i got : 

Detected blocking call to import_module with args ('custom_components.alexa_media',) in /usr/src/homeassistant/homeassistant/loader.py, line 1067: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 322, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)


Other :  
Detected blocking call to listdir with args ('/config/deps/lib/python3.12/site-packages',) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 17: from alexapy import ( (offender: /usr/local/lib/python3.12/site-packages/importlib_metadata/__init__.py, line 727: return os.listdir(self.root or '.')), please create a bug report at https://github.com/alandtse/alexa_media_player/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 322, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path) File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 995, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/config/custom_components/alexa_media/__init__.py", line 17, in <module> from alexapy import (


Other again :  
Enregistreur: homeassistant.loader
Source: loader.py:1067
S'est produit pour la première fois: 17:34:58 (2 occurrences)
Dernier enregistrement: 17:34:58

Unexpected exception importing component custom_components.alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 17, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.12/site-packages/alexapy/__init__.py", line 41, in <module>
    __maintainer__ = metadata["maintainer"]
                     ~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/importlib_metadata/_adapters.py", line 54, in __getitem__
    raise KeyError(item)
KeyError: 'maintainer'

and last one :  
Enregistreur: homeassistant.setup
Source: setup.py:322
S'est produit pour la première fois: 17:34:58 (1 occurrences)
Dernier enregistrement: 17:34:58

Setup failed for custom integration 'alexa_media': Unable to import component: Exception importing custom_components.alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 17, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.12/site-packages/alexapy/__init__.py", line 41, in <module>
    __maintainer__ = metadata["maintainer"]
                     ~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/importlib_metadata/_adapters.py", line 54, in __getitem__
    raise KeyError(item)
KeyError: 'maintainer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.alexa_media

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 17, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.12/site-packages/alexapy/__init__.py", line 41, in <module>
    __maintainer__ = metadata["maintainer"]
                     ~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/importlib_metadata/_adapters.py", line 54, in __getitem__
    raise KeyError(item)
KeyError: 'maintainer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 322, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1078, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.alexa_media

**Comment by st3v3nFr** [comment]
> Also, what is the first alex_media error after restart?

Yep
I upgraded first only HA and everything was working
Next i've update Alexa component, and that was a breaking point

**Comment by st3v3nFr** [comment]
> @st3v3nFr v4.11.4??
Yep !

**Comment by danielbrunt57** [comment]
> Yep I upgraded first only HA and everything was working Next i've update Alexa component, and that was a breaking point

From v4.11.3 to v4.11.4 or from v4.11.2?

**Comment by st3v3nFr** [comment]
> > Yep I upgraded first only HA and everything was working Next i've update Alexa component, and that was a breaking point
> 
> From v4.11.3 to v4.11.4 or from v4.11.2?

the one before i guess, the one i've updated 3 days ago, so it should 4-11-3, but not sure

**Comment by danielbrunt57** [comment]
> File "/usr/local/lib/python3.12/site-packages/alexapy/**init**.py", line 41, in
> **maintainer** = metadata["maintainer"]

That error seems to require this in manifest.json:
```
"requirements": ["alexapy==1.27.10", "packaging>=20.3", "wrapt>=1.14.0", "importlib-metadata==6.8.0"], "
```
I don't have that error and I don't know why some do.  I'm suspecting it's another integration that you have which I don't but I'm only surmising at this point.

This was discussed in https://github.com/alandtse/alexa_media_player/issues/2293#issuecomment-2228153684
```
Hi all.
In my other issue request, @mk-maddin Found out the issue.
https://github.com/alandtse/alexa_media_player/issues/2309#issuecomment-2228078234

Here is a copy past of his solution :

" I was able to work around the issue by "pinning" importlib-metadata to 6.8.0 version (the one mentioned in requirements.txt in AlexaPy package), using the requirements in manifest.json of alexa_media_player package:

"requirements": ["alexapy==1.27.10", "packaging>=20.3", "wrapt>=1.14.0", "importlib-metadata==6.8.0"], "

I did it, reboot twice my HA ( the first boot is doing all the work), and tadaa, everything ios back to normal
```

**Comment by st3v3nFr** [comment]
@danielbrunt57 
" This was discussed in https://github.com/alandtse/alexa_media_player/issues/2293#issuecomment-2228153684 "
Yes, that was me commented that.

Yes, the add [, "importlib-metadata==6.8.0"] did again the trick but the previous update i got was working without that.

Weel, at least this trick (with 2 reboots) still works for now !
Thk you for you asnwer Daniel

**Comment by danielbrunt57** [comment]
> Yes, that was me commented that.

Oops! My bad...

> Yes, the add [, "importlib-metadata==6.8.0"] did again the trick but the previous update i got was working without that.

That's bizarre!  Seems like it might be a race to see who can get their first metadata registered!

> Well, at least this trick (with 2 reboots) still works for now ! 

I wish I knew what's really going on...

> Thk you for you asnwer Daniel

You're welcome!

**Comment by danielbrunt57** [comment]
@alandtse Please close this as resolved. Thanks.
