### ISSUE TITLE
Unable to select dev version

### ISSUE THREAD

**Issue by rayzorben** [alandtse/alexa_media_player#2316]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
HACS is removing the ability to select a version as part of the interface. As it currently stands I cannot select any version other than the latest. HACS recommends calling the update service to install, which I did but fails with this

2024-07-15 07:59:42.375 ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API: 
2024-07-15 10:14:34.855 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/alandtse/alexa_media_player/releases/download/dev/alexa_media.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 730, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/alandtse/alexa_media_player/releases/download/dev/alexa_media.zip

**To Reproduce**

Install alexa media player
Call update service with `dev` as the version.

**Expected behavior**

HACS downloads and installs the dev version.

**Screenshots**
![image](https://github.com/user-attachments/assets/bb3842e0-2a8a-45da-a318-c257cc24dd2a)

**System details**

- Home-assistant (version): 
- Core
2024.7.2
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240710.0
- alexa_media (version from `const.py` or HA startup): 4.10.3
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : Y

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

2024-07-15 07:59:42.375 ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API: 
2024-07-15 10:14:34.855 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/alandtse/alexa_media_player/releases/download/dev/alexa_media.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 730, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/alandtse/alexa_media_player/releases/download/dev/alexa_media.zip

**Comment by alandtse** [comment]
That section is currently empty.

**Comment by alandtse** [comment]
There are no features currently being developed.

**Comment by rayzorben** [comment]
> There are no features currently being developed.

So the 'show devices connected to echo' should be working in the main branch on 4.10.3?
