### ISSUE TITLE
Service notify.alexa_media_last_called not found

### ISSUE THREAD

**Issue by ahahamyan** [alandtse/alexa_media_player#2325]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

When my HA script tries to call service: notify.alexa_media_last_called, receives the exception trace in the logs section below and function is not found. This started occurring after the latest Alexa Media Player update today 4.11.0. This is the approach where I am able to invoke an HA script via Alexa command and have it announce the response from HA script via an announcement on the same device I spoke to. The HA script also calls alexa_media.update_last_called service before calling the notify.alexa_media_last_called which is now missing. Please help. 

**To Reproduce**

create a script and configure as 

service: notify.alexa_media_last_called
data:
  message: |
    Testing
  title: Home Assistant
  data:
    type: tts

**Expected behavior**

to have Home Assistant find the service and execute as before

**System details**

- Home-assistant (version): 2024.7.2
- alexa_media (version from `const.py` or HA startup): 4.11.0
- alexapy (version from `pip show alexapy` or HA startup): 4.11.0
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Logs**

2024-07-18 15:58:55.540 ERROR (MainThread) [alexapy.alexaapi] Giving up _static_request(...) after 5 tries (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests)
2024-07-18 15:58:55.541 WARNING (MainThread) [alexapy.helpers] alexaapi.get_customer_history_records((<alexapy.alexalogin.AlexaLogin object at 0x7faa0b8d8f80>,), {'max_record_size': 10}): An error occurred accessing AlexaAPI: An exception of type AlexapyTooManyRequestsError occurred. Arguments:
('Too Many Requests',)
2024-07-18 15:58:55.541 WARNING (MainThread) [alexapy.helpers] alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7faa0b8d8f80>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyTooManyRequestsError occurred. Arguments:
('Too Many Requests',)
2024-07-18 15:58:55.541 ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API: Too Many Requests
2024-07-18 15:58:58.230 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-07-18 15:59:46.776 WARNING (SyncWorker_17) [urllib3.connectionpool] Connection pool is full, discarding connection: api.ring.com. Connection pool size: 10
2024-07-18 15:59:46.779 WARNING (SyncWorker_13) [urllib3.connectionpool] Connection pool is full, discarding connection: api.ring.com. Connection pool size: 10
2024-07-18 16:01:04.444 ERROR (MainThread) [homeassistant.components.script.activate_locate_jacqueline] Activate Test Speech : Error executing script. Service not found for call_service at pos 3: Service notify.alexa_media_last_called not found
2024-07-18 16:01:04.447 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 652, in _async_run
return await self.script.async_run(script_vars, context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1770, in async_run
return await asyncio.shield(create_eager_task(run.async_run()))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 465, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 529, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 527, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
response_data = await self._async_run_long_action(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
return await long_task
^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2664, in async_call
raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Service notify.alexa_media_last_called not found

**Additional context**

I am adding this link that provides additional context on how this approach is used with Echo's and HA to simulate a request / response . https://community.home-assistant.io/t/ha-to-respond-to-echo-spoken-to/421614/12

**Comment by Lord2666** [comment]
same problem, looking at integrations, the alexa media player integration indicates that it has not been loaded, pressing to restart does not work. Saludos

**Comment by derolli1976** [comment]
Same issue here. Additionally:
The original service "notify.alexa_media_last_called" ist no longer there but there is a "notify.alexa_media_player_last_called_<email>" service now.
It can be accessed via developer tools, but is not recognized in automations.
![image](https://github.com/user-attachments/assets/f4a990c4-29c6-4211-9e02-1f85e9448e87)
![image](https://github.com/user-attachments/assets/a1446d82-bb87-4eeb-a7f4-bb2ffe7a0f7f)

Spook is also finding issues in all automations using the "old" service.

**Comment by ahahamyan** [comment]
> notify.alexa_media_player_last_called_

I do not see a service called notify.alexa_media_player_last_called

**Comment by derolli1976** [comment]
> > notify.alexa_media_player_last_called_
> 
> I do not see a service called notify.alexa_media_player_last_called

Sorry. There's been a typo in my reply. For me, in the developer tools, there is now a service called "notify.alexa_media_last_called_(email)" where (email) is the address of my amazon account.

I.e.: notify.alexa_media_last_called_my_emailaddress_com

**Comment by ahahamyan** [comment]
Just upgraded to Core 2024.7.3 that was released today and now the service is appearing and existing scripts are working again. Thanks all.
