### ISSUE TITLE
500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by Pico1965** [alandtse/alexa_media_player#2333]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

At the end of the configuration, after entering the capcha the error appears:
500 Internal Server Error 
Server got itself in trouble

**To Reproduce**

1. Go to Settings
2. Click on Devices & Services
3. Scroll down to Alexa Media Player
4. Configure until capcha solved

**System details**

HA:
Core 2024.7.3
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes

Integration:
alexa_media_player: 4.11.**1**

**Logs**
```
2024-07-20 12:23:52.086 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 32, in read
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

**Comment by gitcak** [comment]
I'm having the same issue. I cannot go into the integration to configure it. I have it setup already, but the logs are giving errors.

**Comment by DarcyDetlor** [comment]
I am having the same problem, but the error message appears immediately after selecting the CONFIGURE option.  My log files displays this when restarting HA:

`Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 7:20:45 AM (2 occurrences)
Last logged: 7:32:30 AM

Error setting up entry x@gmail.com - amazon.ca for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 337, in async_setup_entry
    if await test_login_status(hass, config_entry, login):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 1384, in test_login_status
    ] = await hass.config_entries.flow.async_init(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1267, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1297, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 518, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 555, in async_step_reauth
    reauth_schema = self._update_schema_defaults()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 803, in _update_schema_defaults
    default=self.config_entry.options.get(CONF_QUEUE_DELAY, 1.5),
            ^^^^^^^^^^^^^^^^^
AttributeError: 'AlexaMediaFlowHandler' object has no attribute 'config_entry'`

**Comment by jackyaz** [comment]
4.11.1 at least loads the configure model now, but its largely blank...
![image](https://github.com/user-attachments/assets/2e887543-bb8d-4bd4-9557-cf94be692cd6)

**Comment by javiges** [comment]
> 4.11.1 al menos carga el modelo de configuración ahora, pero está en gran medida en blanco... ![image](https://private-user-images.githubusercontent.com/6189420/350702478-2e887543-bb8d-4bd4-9557-cf94be692cd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0OTU0MjUsIm5iZiI6MTcyMTQ5NTEyNSwicGF0aCI6Ii82MTg5NDIwLzM1MDcwMjQ3OC0yZTg4NzU0My1iYjhkLTRiZDQtOTU1Ny1jZjk0YmU2OTJjZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjBUMTcwNTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2VkYmU3ODE2ZTlmOTAwMzI2NjFlYzViMzQ4MmRlNmNhOGZlOWVhZjY0N2Q5ZjQ0ZGM1MDdjMjUwYmZiOGE1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bgd_cuEHAp0SiMlSKrlg5JJrnLABfvmJRZUDLhQO0A0)

I also lack the information that has to go in the boxes, I don't know what to put

**Comment by danielbrunt57** [comment]
We have to wait for lokalize to translate the new strings.json.  it will be coming soon.
For now, here are the descriptors:

```
          "include_devices": "Included device (comma separated)",
          "exclude_devices": "Excluded device (comma separated)",
          "scan_interval": "Seconds between scans",
          "queue_delay": "Seconds to wait to queue commands together",
          "extended_entity_discovery": "Include devices connected via Echo",
          "debug": "Advanced debugging"
```
![image](https://github.com/user-attachments/assets/38f9a756-0788-4599-97e2-62ef84f7a038)

**Comment by dCatfish** [comment]
4.11.2 is even worse than the two predecessor versions. OK - "Options" box are still missing descriptions, but now it doesn't even matter what you type in or choose, because it's not being saved when you click "SUBMIT".

**Comment by danielbrunt57** [comment]
> AttributeError: 'AlexaMediaFlowHandler' object has no attribute 'config_entry'`

This has been fixed via PR #2342

**Comment by danielbrunt57** [comment]
> but now it doesn't even matter what you type in or choose, because it's not being saved when you click "SUBMIT"

Damn, your're right!  It _was_ working.
I'm on it...

**Comment by dCatfish** [comment]
> > but now it doesn't even matter what you type in or choose, because it's not being saved when you click "SUBMIT"
> 
> Damn, your're right! It _was_ working. I'm on it...

Thank you! And I must say I'm impressed by the effort you put in to this, without getting anything in return, besides our complaints :)

**Comment by danielbrunt57** [comment]
> Thank you! And I must say I'm impressed by the effort you put in to this, without getting anything in return, besides our complaints :)

Thanks for the thank you and the compliment.  The complaints I don't need!
I'm new to all this python stuff and this is my first try at modifying an integration so please go easy on me!
Alan is still in the background handing pull requests but that's pretty much it.

**Comment by danielbrunt57** [comment]
PR #2343 is submitted...

**Comment by danielbrunt57** [comment]
I think I now need to add a listener in __init__.py to handle options update and reload the integration with the new settings?

**Comment by Pico1965** [comment]
Problem persist in 4.11.**3**

`2024-07-21 09:21:24.115 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 32, in read
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

`

**Comment by danielbrunt57** [comment]
@Pico1965 
> Problem persist in 4.11.**3**

That is not an issue with alexa media player.  It's an httpx read timeout  within the Python 3.12 httpx package that drives Home Assistant and it's likely an IPv6 timeout.

```
File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
raise mapped_exc(message) from exc
httpx.ReadTimeout
```

**Comment by danielbrunt57** [comment]
en and it translation strings are on there way...

 2 hours ago:
> updated the translation files it.json and en.json with the missing strings. I also reordered the various strings in the same order as the strings.json file.

![image](https://github.com/user-attachments/assets/15d22869-d841-4fff-8c5c-84f8e95a578c)
