### ISSUE TITLE
upgrade to 4.12.2 reults with Setup failed for custom integration 'alexa_media'

### ISSUE THREAD

**Issue by wallyto** [alandtse/alexa_media_player#2388]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

**To Reproduce**

1. HACS upgrades to v4.12.2
**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version): 
- Core 2024.7.4
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0

- alexa_media (version from `const.py` or HA startup): v4.12.2
- alexapy (version from `pip show alexapy` or HA startup): 
- ➜  alexa_media pwd             
/root/config/custom_components/alexa_media
➜  alexa_media pip show alexapy
WARNING: Package(s) not found: alexapy
➜  alexa_media pip show alexa.py
WARNING: Package(s) not found: alexa.py
➜  alexa_media 
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Logger: homeassistant.setup Source: setup.py:322 First occurred: August 1, 2024 at 9:30:09 PM (1 occurrences) Last logged: August 1, 2024 at 9:30:09 PM
Setup failed for custom integration 'alexa_media': Unable to import component: cannot import name 'async_creat' from 'homeassistant.components.persistent_notification' (/usr/src/homeassistant/homeassistant/components/persistent_notification/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 30, in <module>
    from homeassistant.components.persistent_notification import async_creat
ImportError: cannot import name 'async_creat' from 'homeassistant.components.persistent_notification' (/usr/src/homeassistant/homeassistant/components/persistent_notification/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 322, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 30, in <module>
    from homeassistant.components.persistent_notification import async_creat
ImportError: cannot import name 'async_creat' from 'homeassistant.components.persistent_notification' (/usr/src/homeassistant/homeassistant/components/persistent_notification/__init__.py)

**Additional context**

**Comment by alandtse** [comment]
Try 4.12.4.

**Comment by wallyto** [comment]
4.12.4 resolved the setup issue. Thanks for the quick response.
