### ISSUE TITLE
 async_create() missing 1 required positional argument: 'hass'

### ISSUE THREAD

**Issue by johntdyer** [alandtse/alexa_media_player#2395]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Integration unable to load w/ 2024.8.0b0 or 2024.8.0b1.  

I get this error every time I try and reload the integration 

**Screenshots**

**System details**

- Home-assistant (version): 2004.08.0b1
- alexa_media (version from `const.py` or HA startup):
```
"""
Support to interface with Alexa Devices.

SPDX-License-Identifier: Apache-2.0

For more details about this platform, please refer to the documentation at
https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639
"""

from datetime import timedelta

from homeassistant.const import (
    CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
    CONCENTRATION_PARTS_PER_MILLION,
    PERCENTAGE,
)

__version__ = "4.12.4"
PROJECT_URL = "https://github.com/alandtse/alexa_media_player/"
ISSUE_URL = f"{PROJECT_URL}issues"
NOTIFY_URL = f"{PROJECT_URL}wiki/Configuration%3A-Notification-Component#use-the-notifyalexa_media-service"

DOMAIN = "alexa_media"
DATA_ALEXAMEDIA = "alexa_media"

PLAY_SCAN_INTERVAL = 20
SCAN_INTERVAL = timedelta(seconds=60)
MIN_TIME_BETWEEN_SCANS = SCAN_INTERVAL
MIN_TIME_BETWEEN_FORCED_SCANS = timedelta(seconds=1)

ALEXA_COMPONENTS = [
    "media_player",
]
DEPENDENT_ALEXA_COMPONENTS = [
    "notify",
    "switch",
    "sensor",
    "alarm_control_panel",
    "light",
    "binary_sensor",
]

HTTP_COOKIE_HEADER = "# HTTP Cookie File"
CONF_ACCOUNTS = "accounts"
CONF_DEBUG = "debug"
CONF_HASS_URL = "hass_url"
CONF_INCLUDE_DEVICES = "include_devices"
CONF_EXCLUDE_DEVICES = "exclude_devices"
CONF_QUEUE_DELAY = "queue_delay"
CONF_PUBLIC_URL = "public_url"
CONF_EXTENDED_ENTITY_DISCOVERY = "extended_entity_discovery"
CONF_SECURITYCODE = "securitycode"
CONF_OTPSECRET = "otp_secret"
CONF_PROXY = "proxy"
CONF_PROXY_WARNING = "proxy_warning"
CONF_TOTP_REGISTER = "registered"
CONF_OAUTH = "oauth"
DATA_LISTENER = "listener"

EXCEPTION_TEMPLATE = "An exception of type {0} occurred. Arguments:\n{1!r}"

DEFAULT_SCAN_INTERVAL = 60
DEFAULT_QUEUE_DELAY = 1.5
DEFAULT_PUBLIC_URL = ""
DEFAULT_EXTENDED_ENTITY_DISCOVERY = False
DEFAULT_DEBUG = False
SERVICE_CLEAR_HISTORY = "clear_history"
SERVICE_UPDATE_LAST_CALLED = "update_last_called"
SERVICE_FORCE_LOGOUT = "force_logout"

RECURRING_PATTERN = {
    None: "Never Repeat",
    "P1D": "Every day",
    "P1M": "Every month",
    "XXXX-WE": "Weekends",
    "XXXX-WD": "Weekdays",
    "XXXX-WXX-1": "Every Monday",
    "XXXX-WXX-2": "Every Tuesday",
    "XXXX-WXX-3": "Every Wednesday",
    "XXXX-WXX-4": "Every Thursday",
    "XXXX-WXX-5": "Every Friday",
    "XXXX-WXX-6": "Every Saturday",
    "XXXX-WXX-7": "Every Sunday",
}

RECURRING_DAY = {
    "MO": 1,
    "TU": 2,
    "WE": 3,
    "TH": 4,
    "FR": 5,
    "SA": 6,
    "SU": 7,
}
RECURRING_PATTERN_ISO_SET = {
    None: {},
    "P1D": {1, 2, 3, 4, 5, 6, 7},
    "XXXX-WE": {6, 7},
    "XXXX-WD": {1, 2, 3, 4, 5},
    "XXXX-WXX-1": {1},
    "XXXX-WXX-2": {2},
    "XXXX-WXX-3": {3},
    "XXXX-WXX-4": {4},
    "XXXX-WXX-5": {5},
    "XXXX-WXX-6": {6},
    "XXXX-WXX-7": {7},
}

ATTR_MESSAGE = "message"
ATTR_EMAIL = "email"
ATTR_NUM_ENTRIES = "entries"
STARTUP = f"""
-------------------------------------------------------------------
{DOMAIN}
Version: {__version__}
This is a custom component
If you have any issues with this you need to open an issue here:
{ISSUE_URL}
-------------------------------------------------------------------
"""

AUTH_CALLBACK_PATH = "/auth/alexamedia/callback"
AUTH_CALLBACK_NAME = "auth:alexamedia:callback"
AUTH_PROXY_PATH = "/auth/alexamedia/proxy"
AUTH_PROXY_NAME = "auth:alexamedia:proxy"

ALEXA_UNIT_CONVERSION = {
    "Alexa.Unit.Percent": PERCENTAGE,
    "Alexa.Unit.PartsPerMillion": CONCENTRATION_PARTS_PER_MILLION,
    "Alexa.Unit.Density.MicroGramsPerCubicMeter": CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
}

ALEXA_ICON_CONVERSION = {
    "Alexa.AirQuality.CarbonMonoxide": "mdi:molecule-co",
    "Alexa.AirQuality.Humidity": "mdi:water-percent",
    "Alexa.AirQuality.IndoorAirQuality": "mdi:numeric",
}
ALEXA_ICON_DEFAULT = "mdi:molecule"

UPLOAD_PATH = "www/alexa_tts"
```
- alexapy (version from `pip show alexapy` or HA startup):
 ```
2024-08-03 12:42:51.562 INFO (MainThread) [homeassistant.setup] Setting up alexa_media
2024-08-03 12:42:51.562 INFO (MainThread) [homeassistant.setup] Setup of domain alexa_media took 0.00 seconds
2024-08-03 12:42:51.579 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry johntdyer+amazon@gmail.com - amazon.com for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 359, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 328, in load_cookie
--
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 514, in handle_manifest_list
    raise int_or_exc
homeassistant.loader.IntegrationNotFound: Integration 'tesla' not found.
2024-08-03 13:47:01.978 ERROR (SyncWorker_21) [homeassistant] Error doing job: Unclosed client session (None)
2024-08-03 13:47:01.979 ERROR (SyncWorker_21) [homeassistant] Error doing job: Unclosed client session (None)
2024-08-03 13:47:01.980 ERROR (SyncWorker_21) [homeassistant] Error doing job: Unclosed client session (None)
2024-08-03 13:47:23.759 DEBUG (MainThread) [custom_components.alexa_media.helpers] j**************n@g*******m: Returning uuid {'uuid': '525051016264f8b0fb26c5fe3a86e8b6', 'index': 0}
2024-08-03 13:47:23.773 DEBUG (MainThread) [alexapy.alexalogin] Creating TOTP for F************************************************************IXV
2024-08-03 13:47:23.773 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP xxxx
2024-08-03 13:47:23.773 DEBUG (MainThread) [alexapy.alexalogin] Login created for xxxxx+xxxx@gmail.com - amazon.com
2024-08-03 13:47:23.774 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)
2024-08-03 13:47:23.775 DEBUG (MainThread) [alexapy.alexalogin] Searching for cookies from /config/.storage/alexa_media.johntdyer+amazon@gmail.com.pickle
2024-08-03 13:47:23.775 DEBUG (MainThread) [alexapy.alexalogin] Searching for cookies from /config/alexa_media.johntdyer+amazon@gmail.com.pickle
2024-08-03 13:47:23.775 DEBUG (MainThread) [alexapy.alexalogin] Searching for cookies from /config/.storage/alexa_media.johntdyer+amazon@gmail.com.txt
2024-08-03 13:47:23.775 DEBUG (MainThread) [alexapy.alexalogin] Using credentials to log in
2024-08-03 13:47:23.775 DEBUG (MainThread) [alexapy.alexalogin] Loaded last request to https://www.amazon.com/ap/cvf/verify
2024-08-03 13:47:23.775 DEBUG (MainThread) [alexapy.alexalogin] Processing https://www.amazon.com/ap/cvf/verify
2024-08-03 13:47:23.785 DEBUG (MainThread) [alexapy.alexalogin] Verification captcha code requested:
2024-08-03 13:47:23.786 DEBUG (MainThread) [alexapy.alexalogin] Found post url to verify; converting to https://www.amazon.com/ap/cvf/verify
2024-08-03 13:47:23.786 DEBUG (MainThread) [alexapy.alexalogin] Preparing form submission to https://www.amazon.com/ap/cvf/verify with input data: {}
2024-08-03 13:47:23.786 DEBUG (MainThread) [alexapy.alexalogin] No 2FA code supplied but will generate.
2024-08-03 13:47:23.786 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP xxxxxx
2024-08-03 13:47:24.253 DEBUG (MainThread) [alexapy.alexalogin] POST:
https://www.amazon.com/ap/cvf/verify returned 200:OK with response <CIMultiDictProxy('Content-Type': 'text/html;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'Server', 'Date': 'Sat, 03 Aug 2024 17:47:23 GMT', 'x-amz-rid': 'xxxxxx', 'Set-Cookie': 'lc-main=en_US; Domain=.amazon.com; Expires=Tue, 01 Jan 2036 08:00:01 GMT; Path=/; Secure', 'Set-Cookie': 'session-id=145-9004754-8352717; Domain=.amazon.com; Expires=Tue, 01 Jan 2036 08:00:01 GMT; Path=/; Secure', 'Set-Cookie': 'session-id-time=2082787201l; Domain=.amazon.com; Expires=Tue, 01 Jan 2036 08:00:01 GMT; Path=/; Secure', 'Set-Cookie': 'session-token=xxxxx; Domain=.amazon.com; Expires=Tue, 01 Jan 2036 08:00:01 GMT; Path=/; Secure; HttpOnly', 'Pragma': 'no-cache', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Cache-Control': 'no-cache', 'Cache-Control': 'no-store', 'Content-Encoding': 'gzip', 'Content-Language': 'und', 'Vary': 'accept-encoding,Content-Type,Accept-Encoding,User-Agent', 'Strict-Transport-Security': 'max-age=47474747; includeSubDomains; preload', 'X-Frame-Options': 'SAMEORIGIN', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 xxxx.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ATL58-P5', 'Alt-Svc': 'h3=":443"; ma=86400', 'X-Amz-Cf-Id': 'xxx-xx==')>
2024-08-03 13:47:24.254 DEBUG (MainThread) [alexapy.alexalogin] Processing https://www.amazon.com/ap/cvf/verify
2024-08-03 13:47:24.343 DEBUG (MainThread) [alexapy.alexalogin] Verification captcha code requested:
2024-08-03 13:47:24.343 DEBUG (MainThread) [alexapy.alexalogin] Found post url to verify; converting to https://www.amazon.com/ap/cvf/verify
➜  custom_components
```

- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Logs**

```
2024-08-03 13:47:23.759 DEBUG (MainThread) [custom_components.alexa_media.helpers] j**************n@g*******m: Returning uuid {'uuid': '525051016264f8b0fb26c5fe3a86e8b6', 'index': 0}
2024-08-03 13:47:23.773 DEBUG (MainThread) [alexapy.alexalogin] Creating TOTP for F************************************************************IXV
2024-08-03 13:47:23.773 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP 881315
2024-08-03 13:47:23.773 DEBUG (MainThread) [alexapy.alexalogin] Login created for johntdyer+amazon@gmail.com - amazon.com
2024-08-03 13:47:23.774 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)
2024-08-03 13:47:23.775 DEBUG (MainThread) [alexapy.alexalogin] Searching for cookies from /config/.storage/alexa_media.johntdyer+amazon@gmail.com.pickle
2024-08-03 13:47:23.775 DEBUG (MainThread) [alexapy.alexalogin] Searching for cookies from /config/alexa_media.johntdyer+amazon@gmail.com.pickle
2024-08-03 13:47:23.775 DEBUG (MainThread) [alexapy.alexalogin] Searching for cookies from /config/.storage/alexa_media.johntdyer+amazon@gmail.com.txt
2024-08-03 13:47:23.775 DEBUG (MainThread) [alexapy.alexalogin] Using credentials to log in
2024-08-03 13:47:23.775 DEBUG (MainThread) [alexapy.alexalogin] Loaded last request to https://www.amazon.com/ap/cvf/verify
2024-08-03 13:47:23.775 DEBUG (MainThread) [alexapy.alexalogin] Processing https://www.amazon.com/ap/cvf/verify
2024-08-03 13:47:23.785 DEBUG (MainThread) [alexapy.alexalogin] Verification captcha code requested:
2024-08-03 13:47:23.786 DEBUG (MainThread) [alexapy.alexalogin] Found post url to verify; converting to https://www.amazon.com/ap/cvf/verify
2024-08-03 13:47:23.786 DEBUG (MainThread) [alexapy.alexalogin] Preparing form submission to https://www.amazon.com/ap/cvf/verify with input data: {}
2024-08-03 13:47:23.786 DEBUG (MainThread) [alexapy.alexalogin] No 2FA code supplied but will generate.
2024-08-03 13:47:23.786 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP 881315
2024-08-03 13:47:24.253 DEBUG (MainThread) [alexapy.alexalogin] POST:
https://www.amazon.com/ap/cvf/verify returned 200:OK with response <CIMultiDictProxy('Content-Type': 'text/html;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'Server', 'Date': 'Sat, 03 Aug 2024 17:47:23 GMT', 'x-amz-rid': 'xxxxxxxxxxx', 'Set-Cookie': 'lc-main=en_US; Domain=.amazon.com; Expires=Tue, 01 Jan 2036 08:00:01 GMT; Path=/; Secure', 'Set-Cookie': 'session-id=145-xxxxxxxx-8352717; Domain=.amazon.com; Expires=Tue, 01 Jan 2036 08:00:01 GMT; Path=/; Secure', 'Set-Cookie': 'session-id-time=2082787201l; Domain=.amazon.com; Expires=Tue, 01 Jan 2036 08:00:01 GMT; Path=/; Secure', 'Set-Cookie': 'session-token=UYxxxxxxxxxxGMT; Path=/; Secure; HttpOnly', 'Pragma': 'no-cache', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Cache-Control': 'no-cache', 'Cache-Control': 'no-store', 'Content-Encoding': 'gzip', 'Content-Language': 'und', 'Vary': 'accept-encoding,Content-Type,Accept-Encoding,User-Agent', 'Strict-Transport-Security': 'max-age=47474747; includeSubDomains; preload', 'X-Frame-Options': 'SAMEORIGIN', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 xxxxxxxxx.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ATL58-P5', 'Alt-Svc': 'h3=":443"; ma=86400', 'X-Amz-Cf-Id': 'xxxx-xxxxxx==')>
2024-08-03 13:47:24.254 DEBUG (MainThread) [alexapy.alexalogin] Processing https://www.amazon.com/ap/cvf/verify
2024-08-03 13:47:24.343 DEBUG (MainThread) [alexapy.alexalogin] Verification captcha code requested:
2024-08-03 13:47:24.343 DEBUG (MainThread) [alexapy.alexalogin] Found post url to verify; converting to https://www.amazon.com/ap/cvf/verify
2024-08-03 13:47:24.343 DEBUG (MainThread) [custom_components.alexa_media] Testing login status: {'captcha_required': True, 'captcha_image_url': 'https://opfcaptcha-prod.s3.amazonaws.com/6dd7fd5ae59749aeb722b9f22ba17fd6.jpg?AWSAccessKeyId=xxxx&Expires=1722707543&Signature=xxxx%3D', 'verification_captcha_required': True}
2024-08-03 13:47:24.343 DEBUG (MainThread) [custom_components.alexa_media] Logging in: {'url': 'amazon.com', 'otp_secret': 'F************************************************************IXV', 'email': 'j**************n@g*******m', 'password': 'REDACTED 19 CHARS', 'scan_interval': 60, 'queue_delay': 1.5, 'include_devices': '', 'exclude_devices': '', 'extended_entity_discovery': False, 'debug': False, 'oauth': {'access_token': 'A***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************qhQ', 'refresh_token': 'A*************************************************************************************************************************************************************************************************************************************************************************************************************************************************************IOt', 'expires_in': 1722472233.624294, 'mac_dms': {'device_private_key': 'xxxxx/mxq5+S40mQ7/FLdV5gbl5b3cUarhz7bkjng4uj84iuO5eFlFVlmpL/eFM9L0NQbrFR0vHS7v1NovbG7w+cgUeRRa+qzz/xxx+tyDdOr37JTR3Xlwyqhv/1Lvq3jRVAdZwG+NbAEsDqnmhF30YJGFeaE0K1ba2TQHFMDh09POLnYUbwJ9PxsD5kZOcK54C7Xhb5rSm5Dnx1m3MB3pE/IQg/hK+Vqgkk+xxxxxx/+oyOBl/BD1WBrE9ocZacTCIGb7skft6qNXHXs6xUiPQKBgQDdWpNzbA0fUp4FBsEpoa0yM4/2o+4UHEVG8VUdl3dFfPcOZ/3K+2xLTIQ5emEBt+IssLG/QvW5TRm1iKjhZZBY+mNSIt9M7ptaRMZeEBO7P5e0YdpvMHhnAY8EYULDosgOIE2RaMBiFCptwT5YeDlsa0eYG3QUhVbpjXnQBf4XIg==', 'adp_token': '{enc:UcOhoMtAEzUjYks9u6YTkLFMtsF7oyylF3Zgq4vFg7dOvjPQMW1iPxrU8SZNzcee5JKokfJ+12N4ZkIl/nlXq/xxxxx/KSus4+AuaZF/fhbPUsoWHwWIZaUEst+88IxJZhmVoZ6Sozk2M5YKUBjBSH5ur1SZs7hQYW3mk+/Kl/UcvZSS8qDQzQUVFRFlszWgCHTYHDkzD5unDkLnw6XCZMlcM/XjGaot/nCWKZeHzNwbhW4LuB8LoUx5/kgFXPX1e754EcxxCBeIJ0oPMbRIWgOpcJolCBMhSN3s1eKuN+wF4rvJZ+SD0D/xxxxxxx+hO3GzAA7klmM9Qupq2GXJpXZRV8HVCsRmtUH9AFNKzgZl1W7ON6Cme65PdjCZH5jX+lM8PxhWCWKrJ/VPigD8POS45ibFmpob8RWZcwyCKhgRTlrC8RkE4emvAnFzysOeG+hf2vWIp8H/xxxxxx/0tro57bZ8GAzR/WRCS3ZteaYD0EkVndBW2Z8LQR+01/EHxuNDyaw7AnVRyD0Ap82SCVYsSxlBRulD0TFScelYsRqHMeaRNrS8YKZN4iRVI6npdFD+Gh46VkTHRMdxps8VddCPTZT6H4/Sg4x7z2vjMpjitHEV6fwWXvaYrkYqsdxFCb0usQ+4SKFzzDNhv3TdSR9ZZc/FhMRh0SSbMDL5m293vga7/xxxxx/xxx/ELWmRiMVmbkupNt6QUt/RCND8/eWmLBVbeTEUTt+uXE7ocmKJIRPluEIFKOMvH0tJDV/xxxx=}{key:gmfZ1XGhgKRmV27jtBJkTt9iW8kWGIZ9lYl+AVfy52U0we+p8wh9MoC4uioCeyFMQSgI7+GVr7H+T+AoTOG1tEA1vXCsjwS/bfY6U4nrh0laKDZ4ffPQAf3SzxedXwEjEf0hCSVjl7NOHoczfz9CV7F0tF0htplPwW8KbS27lC9GjEaTo7F5xXtpPV4i3pdYNLbezab25ao9Fsm0k3efHtmJQdccMyl5By3JjgiOEn6nTcBGv9Kv1inYFG8kZ1+xxxx==}{iv:r/90+67+63+1wiE/gIfJ+Q==}{name:QURQVG9rZW5FbmNyeXB0aW9uS2V5}{serial:Mg==}'}, 'code_verifier': '6LZODYZQ_7WDE1jkv78J5N4WrdJ9WJfyggsiyN733F0', 'authorization_code': 'ANPBjPmxASyzhYpeKUBHKfnf'}} {'01J4CJ2PTM6B0SSW7D7N97JSRP'}
2024-08-03 13:47:24.344 DEBUG (MainThread) [custom_components.alexa_media] Login stats: {'login_timestamp': datetime.datetime(1, 1, 1, 0, 0), 'api_calls': 0}
2024-08-03 13:47:24.344 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry johntdyer+amazon@gmail.com - amazon.com for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 360, in async_setup_entry
    if await test_login_status(hass, config_entry, login):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 1396, in test_login_status
    async_create_persistent_notification(
TypeError: async_create() missing 1 required positional argument: 'hass'
```

**Additional context**

**Comment by johntdyer** [comment]
Noticed a similar error ( https://github.com/danieldotnl/ha-multiscrape/issues/391 ) from multiscrape as well

**Comment by rlust** [comment]
Same issue, not getting option to reconfigure

**Comment by ChristophCaina** [comment]
see #2392

**Comment by danielbrunt57** [comment]
closed this as [completed](https://github.com/alandtse/alexa_media_player/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/alandtse/alexa_media_player/commit/b700ac78929e430bae7c630c67c26b2212a2774b
