### ISSUE TITLE
Unauthorized when configured AMP

### ISSUE THREAD

**Issue by samsonusmc** [alandtse/alexa_media_player#2410]
When configuring a AMP 4.12.5 with HA 2024.8.0b8 getting errors after adding integration and it does not load Alexa devices

**To Reproduce**

Configure integration

**Expected behavior**

Expected to load Alexa devices but errors in logs show unauthorized

- Home-assistant (version): 2024.8.0b8
- alexa_media (version from `const.py` or HA startup): 4.12.5
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Logs**
`2024-08-07 07:56:00.837 WARNING (MainThread) [alexapy.helpers] alexaapi.get_guard_details((<alexapy.alexalogin.AlexaLogin object at 0xffff4e5ece60>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Unauthorized',)
2024-08-07 07:56:00.837 WARNING (MainThread) [alexapy.helpers] alexaapi.get_network_details((<alexapy.alexalogin.AlexaLogin object at 0xffff4e5ece60>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Unauthorized',)
2024-08-07 07:56:00.849 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/__init__.py", line 251, in relogin
    if await test_login_status(hass, config_entry, login_obj):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 1421, in test_login_status
    ] = await hass.config_entries.flow.async_init(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1293, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1323, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 578, in async_step_reauth
    reauth_schema = self._update_schema_defaults()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 815, in _update_schema_defaults
    CONF_HASS_URL, default=self.config.get(CONF_HASS_URL, hass_url)
                                                          ^^^^^^^^
NameError: name 'hass_url' is not defined
`

**Additional context**

**Comment by samsonusmc** [comment]
Duplicate of https://github.com/alandtse/alexa_media_player/issues/2406
