### ISSUE TITLE
NameError: name 'hass_url' is not defined

### ISSUE THREAD

**Issue by Drewskieza** [alandtse/alexa_media_player#2424]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After installing 2024.8.0 Alexa Media Player fails to setup.
Error in logs NameError: name 'hass_url' is not defined

**To Reproduce**

1. Install 2024.8.0
2. restart HA
3. Fails to start and produces the error

**Expected behavior**

Integration to start

**Screenshots**

**System details**

- Home-assistant (version): 2024.8.0
- alexa_media (version from `const.py` or HA startup): HA OS
- alexapy (version from `pip show alexapy` or HA startup): HA OS
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :y

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

`
2024-08-08 08:35:28.866 DEBUG (MainThread) [custom_components.alexa_media.helpers] d*********a@g*******m: Returning uuid {'uuid': 'a586a033d706730c840b052a84d092e4', 'index': 0}
2024-08-08 08:35:28.885 DEBUG (MainThread) [alexapy.alexalogin] Creating TOTP for 5************************************************A3Q
2024-08-08 08:35:28.885 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP 316454
2024-08-08 08:35:28.885 DEBUG (MainThread) [alexapy.alexalogin] Login created for d*********a@g*******m - amazon.co.uk
2024-08-08 08:35:28.886 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)
2024-08-08 08:35:28.887 DEBUG (MainThread) [alexapy.alexalogin] Searching for cookies from /config/.storage/alexa_media.d*********a@g*******m.pickle
2024-08-08 08:35:28.887 DEBUG (MainThread) [alexapy.alexalogin] Searching for cookies from /config/alexa_media.d*********a@g*******m.pickle
2024-08-08 08:35:28.887 DEBUG (MainThread) [alexapy.alexalogin] Searching for cookies from /config/.storage/alexa_media.d*********a@g*******m.txt
2024-08-08 08:35:28.887 DEBUG (MainThread) [alexapy.alexalogin] Using credentials to log in
2024-08-08 08:35:28.887 DEBUG (MainThread) [alexapy.alexalogin] Attempting oauth login to https://www.amazon.com/ap/signin?openid.return_to=https://www.amazon.com/ap/maplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:613538366130333364373036373330633834306230353261383464303932653432333431333234393536346335363335353634643332353733383331&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.response_type=code&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&openid.oa2.code_challenge_method=S256&openid.oa2.code_challenge=wG9WXTMfoLswGfPoEauqalL1hUhUbqVzI0Bdp0iCes4&language=en_GB
2024-08-08 08:35:28.888 DEBUG (MainThread) [alexapy.alexalogin] Loaded last request to https://www.amazon.com/ap/signin?openid.return_to=https://www.amazon.com/ap/maplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:613538366130333364373036373330633834306230353261383464303932653432333431333234393536346335363335353634643332353733383331&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.response_type=code&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&openid.oa2.code_challenge_method=S256&openid.oa2.code_challenge=wG9WXTMfoLswGfPoEauqalL1hUhUbqVzI0Bdp0iCes4&language=en_GB 
2024-08-08 08:35:28.888 DEBUG (MainThread) [alexapy.alexalogin] Processing https://www.amazon.com/ap/signin?openid.return_to=https://www.amazon.com/ap/maplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:613538366130333364373036373330633834306230353261383464303932653432333431333234393536346335363335353634643332353733383331&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.response_type=code&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&openid.oa2.code_challenge_method=S256&openid.oa2.code_challenge=wG9WXTMfoLswGfPoEauqalL1hUhUbqVzI0Bdp0iCes4&language=en_GB
2024-08-08 08:35:28.896 DEBUG (MainThread) [alexapy.alexalogin] Captcha/2FA not requested; confirming login.
2024-08-08 08:35:28.896 DEBUG (MainThread) [alexapy.alexalogin] Attempting to register with amazon.co.uk
2024-08-08 08:35:29.223 DEBUG (MainThread) [alexapy.alexalogin] auth response <ClientResponse(https://api.amazon.co.uk/auth/register) [400 Bad Request]>
<CIMultiDictProxy('Server': 'Server', 'Date': 'Thu, 08 Aug 2024 07:35:29 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '426', 'Connection': 'keep-alive', 'x-amz-rid': 'C0HMNM9FJVPTW8CJEX0Q', 'x-amzn-RequestId': 'f764e5a2-6214-495f-8d2c-8c22122d5c4d', 'X-Amz-Date': 'Thu, 08 Aug 2024 07:35:29 GMT', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Vary': 'Content-Type,Accept-Encoding,User-Agent', 'Strict-Transport-Security': 'max-age=47474747; includeSubDomains; preload')>
 with 
{"requested_extensions": ["device_info", "customer_info"], "cookies": {"website_cookies": [], "domain": ".amazon.co.uk"}, "registration_data": {"domain": "Device", "app_version": "2.2.556530.0", "device_type": "A2IVLV5VM2W81", "device_name": "%FIRST_NAME%'s%DUPE_STRATEGY_1ST%Alexa Media Player", "os_version": "16.6", "device_serial": "a586a033d706730c840b052a84d092e4", "device_model": "iPhone", "app_name": "Alexa Media Player", "software_version": "1"}, "auth_data": {"client_id": "613538366130333364373036373330633834306230353261383464303932653432333431333234393536346335363335353634643332353733383331", "authorization_code": "ANWHbbUJToeNlkgZndtWwWgI", "code_verifier": "r8C0R8pcvJCQsKrgPVT_zcMCQGJCyfCGEwXvRiwxO4s", "code_algorithm": "SHA-256", "client_domain": "DeviceLegacy"}, "user_context_map": {"frc": "CwyI12pWKHN+smy4ui7CPGjKGKFCtjwAZI1WHCMJ7qIfAtkiYEEHxoVLkVtPUyvTSKz/SFKY2AaDbUH665/iFvVTtu9gGyGmjha9L37C8kHPa26NwGMBq+dKhneIot+jOtl6aNMWRmAXLuBN3qO2Tv0PIIWXf3F/TpiAkfdwPUTpqH3eiJAIV5KRvnvM4ZOWFMVqmI81b6Nkpt0zK6XuVsh1OzMMwqQyieov1mnD50vdj0f3eaZdaWdy42kzJA8ZOPrB7HPNnPqxPB/8Bp6TmMZ3kzIGTxjQHTnEk42fz9QfjQ/auPIrgaBEXGevq7VAOp0e1+wNhdLpUhJ6EeigzVfAAfYpL2LJ8Op9eX4bYJAILNAcb7gNV7C6b3EnrE1/BAkeeevOzIBM83lAOLlo4e937Y4Q82d/1A"}, "requested_token_type": ["bearer", "mac_dms", "website_cookies"]}
2024-08-08 08:35:29.224 DEBUG (MainThread) [alexapy.alexalogin] Attempting to register with amazon.com
2024-08-08 08:35:29.612 DEBUG (MainThread) [alexapy.alexalogin] auth response <ClientResponse(https://api.amazon.com/auth/register) [400 Bad Request]>
<CIMultiDictProxy('Server': 'Server', 'Date': 'Thu, 08 Aug 2024 07:35:29 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '426', 'Connection': 'keep-alive', 'x-amz-rid': 'HFHFJ95J82S4M39K1D6Q', 'x-amzn-RequestId': '1e142965-8390-4843-847b-d09cfd738d3f', 'X-Amz-Date': 'Thu, 08 Aug 2024 07:35:29 GMT', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Vary': 'Content-Type,Accept-Encoding,User-Agent', 'Strict-Transport-Security': 'max-age=47474747; includeSubDomains; preload')>
 with 
{"requested_extensions": ["device_info", "customer_info"], "cookies": {"website_cookies": [], "domain": ".amazon.com"}, "registration_data": {"domain": "Device", "app_version": "2.2.556530.0", "device_type": "A2IVLV5VM2W81", "device_name": "%FIRST_NAME%'s%DUPE_STRATEGY_1ST%Alexa Media Player", "os_version": "16.6", "device_serial": "a586a033d706730c840b052a84d092e4", "device_model": "iPhone", "app_name": "Alexa Media Player", "software_version": "1"}, "auth_data": {"client_id": "613538366130333364373036373330633834306230353261383464303932653432333431333234393536346335363335353634643332353733383331", "authorization_code": "ANWHbbUJToeNlkgZndtWwWgI", "code_verifier": "r8C0R8pcvJCQsKrgPVT_zcMCQGJCyfCGEwXvRiwxO4s", "code_algorithm": "SHA-256", "client_domain": "DeviceLegacy"}, "user_context_map": {"frc": "CwyI12pWKHN+smy4ui7CPGjKGKFCtjwAZI1WHCMJ7qIfAtkiYEEHxoVLkVtPUyvTSKz/SFKY2AaDbUH665/iFvVTtu9gGyGmjha9L37C8kHPa26NwGMBq+dKhneIot+jOtl6aNMWRmAXLuBN3qO2Tv0PIIWXf3F/TpiAkfdwPUTpqH3eiJAIV5KRvnvM4ZOWFMVqmI81b6Nkpt0zK6XuVsh1OzMMwqQyieov1mnD50vdj0f3eaZdaWdy42kzJA8ZOPrB7HPNnPqxPB/8Bp6TmMZ3kzIGTxjQHTnEk42fz9QfjQ/auPIrgaBEXGevq7VAOp0e1+wNhdLpUhJ6EeigzVfAAfYpL2LJ8Op9eX4bYJAILNAcb7gNV7C6b3EnrE1/BAkeeevOzIBM83lAOLlo4e937Y4Q82d/1A"}, "requested_token_type": ["bearer", "mac_dms", "website_cookies"]}
2024-08-08 08:35:29.612 DEBUG (MainThread) [alexapy.alexalogin] Unable to register with ['amazon.co.uk', 'amazon.com']
2024-08-08 08:35:29.770 DEBUG (MainThread) [alexapy.alexalogin] capabilities response <ClientResponse(https://api.amazonalexa.com/v1/devices/@self/capabilities) [403 Forbidden]>
<CIMultiDictProxy('Content-Length': '0', 'Connection': 'keep-alive', 'Server': 'Server', 'Date': 'Thu, 08 Aug 2024 07:35:29 GMT', 'x-amz-rid': '4ZAKVH9DKX32EZ617XEJ', 'Vary': 'Content-Type,Accept-Encoding,User-Agent', 'Strict-Transport-Security': 'max-age=47474747; includeSubDomains; preload', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 6a9ea438bafda34d7b7927bf6f7625fc.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MAN51-P4', 'X-Amz-Cf-Id': '7rYd32CSj7qn0R6vQy-mSqIRblPr4tbUmLoEHqKns2jikRfnZ8uFng==')>
 with 
{"legacyFlags": {"SUPPORTS_COMMS": true, "SUPPORTS_ARBITRATION": true, "SCREEN_WIDTH": 1170, "SUPPORTS_SCRUBBING": true, "SPEECH_SYNTH_SUPPORTS_TTS_URLS": false, "SUPPORTS_HOME_AUTOMATION": true, "SUPPORTS_DROPIN_OUTBOUND": true, "FRIENDLY_NAME_TEMPLATE": "VOX", "SUPPORTS_SIP_OUTBOUND_CALLING": true, "VOICE_PROFILE_SWITCHING_DISABLED": true, "SUPPORTS_LYRICS_IN_CARD": false, "SUPPORTS_DATAMART_NAMESPACE": "Vox", "SUPPORTS_VIDEO_CALLING": true, "SUPPORTS_PFM_CHANGED": true, "SUPPORTS_TARGET_PLATFORM": "TABLET", "SUPPORTS_SECURE_LOCKSCREEN": false, "AUDIO_PLAYER_SUPPORTS_TTS_URLS": false, "SUPPORTS_KEYS_IN_HEADER": false, "SUPPORTS_MIXING_BEHAVIOR_FOR_AUDIO_PLAYER": false, "AXON_SUPPORT": true, "SUPPORTS_TTS_SPEECHMARKS": true}, "envelopeVersion": "20160207", "capabilities": [{"version": "0.1", "interface": "CardRenderer", "type": "AlexaInterface"}, {"interface": "Navigation", "type": "AlexaInterface", "version": "1.1"}, {"type": "AlexaInterface", "version": "2.0", "interface": "Alexa.Comms.PhoneCallController"}, {"type": "AlexaInterface", "version": "1.1", "interface": "ExternalMediaPlayer"}, {"type": "AlexaInterface", "interface": "Alerts", "configurations": {"maximumAlerts": {"timers": 2, "overall": 99, "alarms": 2}}, "version": "1.3"}, {"version": "1.0", "interface": "Alexa.Display.Window", "type": "AlexaInterface", "configurations": {"templates": [{"type": "STANDARD", "id": "app_window_template", "configuration": {"sizes": [{"id": "fullscreen", "type": "DISCRETE", "value": {"value": {"height": 1440, "width": 3200}, "unit": "PIXEL"}}], "interactionModes": ["mobile_mode", "auto_mode"]}}]}}, {"type": "AlexaInterface", "interface": "AccessoryKit", "version": "0.1"}, {"type": "AlexaInterface", "interface": "Alexa.AudioSignal.ActiveNoiseControl", "version": "1.0", "configurations": {"ambientSoundProcessingModes": [{"name": "ACTIVE_NOISE_CONTROL"}, {"name": "PASSTHROUGH"}]}}, {"interface": "PlaybackController", "type": "AlexaInterface", "version": "1.0"}, {"version": "1.0", "interface": "Speaker", "type": "AlexaInterface"}, {"version": "1.0", "interface": "SpeechSynthesizer", "type": "AlexaInterface"}, {"version": "1.0", "interface": "AudioActivityTracker", "type": "AlexaInterface"}, {"type": "AlexaInterface", "interface": "Alexa.Camera.LiveViewController", "version": "1.0"}, {"type": "AlexaInterface", "version": "1.0", "interface": "Alexa.Input.Text"}, {"type": "AlexaInterface", "interface": "Alexa.PlaybackStateReporter", "version": "1.0"}, {"version": "1.1", "interface": "Geolocation", "type": "AlexaInterface"}, {"interface": "Alexa.Health.Fitness", "version": "1.0", "type": "AlexaInterface"}, {"interface": "Settings", "type": "AlexaInterface", "version": "1.0"}, {"configurations": {"interactionModes": [{"dialog": "SUPPORTED", "interactionDistance": {"value": 18, "unit": "INCHES"}, "video": "SUPPORTED", "keyboard": "SUPPORTED", "id": "mobile_mode", "uiMode": "MOBILE", "touch": "SUPPORTED"}, {"video": "UNSUPPORTED", "dialog": "SUPPORTED", "interactionDistance": {"value": 36, "unit": "INCHES"}, "uiMode": "AUTO", "touch": "SUPPORTED", "id": "auto_mode", "keyboard": "UNSUPPORTED"}]}, "type": "AlexaInterface", "interface": "Alexa.InteractionMode", "version": "1.0"}, {"type": "AlexaInterface", "configurations": {"catalogs": [{"type": "IOS_APP_STORE", "identifierTypes": ["URI_HTTP_SCHEME", "URI_CUSTOM_SCHEME"]}]}, "version": "0.2", "interface": "Alexa.Launcher"}, {"interface": "System", "version": "1.0", "type": "AlexaInterface"}, {"interface": "Alexa.IOComponents", "type": "AlexaInterface", "version": "1.4"}, {"type": "AlexaInterface", "interface": "Alexa.FavoritesController", "version": "1.0"}, {"version": "1.0", "type": "AlexaInterface", "interface": "Alexa.Mobile.Push"}, {"type": "AlexaInterface", "interface": "InteractionModel", "version": "1.1"}, {"interface": "Alexa.PlaylistController", "type": "AlexaInterface", "version": "1.0"}, {"interface": "SpeechRecognizer", "type": "AlexaInterface", "version": "2.1"}, {"interface": "AudioPlayer", "type": "AlexaInterface", "version": "1.3"}, {"type": "AlexaInterface", "version": "3.1", "interface": "Alexa.RTCSessionController"}, {"interface": "VisualActivityTracker", "version": "1.1", "type": "AlexaInterface"}, {"interface": "Alexa.PlaybackController", "version": "1.0", "type": "AlexaInterface"}, {"type": "AlexaInterface", "interface": "Alexa.SeekController", "version": "1.0"}, {"interface": "Alexa.Comms.MessagingController", "type": "AlexaInterface", "version": "1.0"}]}
{"User-Agent": "AmazonWebView/Amazon Alexa/2.2.556530.0/iOS/16.6/iPhone", "Accept-Language": "en-US", "Accept-Charset": "utf-8", "Connection": "keep-alive", "Content-type": "application/json; charset=UTF-8", "authorization": "Bearer None"}
2024-08-08 08:35:29.770 DEBUG (MainThread) [alexapy.alexalogin] Failed to register capabilities
2024-08-08 08:35:29.906 DEBUG (MainThread) [alexapy.alexalogin] 5 cookies successfully exchanged for refresh token for domain .amazon.co.uk
2024-08-08 08:35:29.907 DEBUG (MainThread) [alexapy.alexalogin] Attempting to discover CSRF token
2024-08-08 08:35:29.987 DEBUG (MainThread) [alexapy.alexalogin] CSRF token not found from /spa/index.html
2024-08-08 08:35:30.131 DEBUG (MainThread) [alexapy.alexalogin] CSRF token not found from /api/devices-v2/device?cached=false
2024-08-08 08:35:30.160 DEBUG (MainThread) [alexapy.alexalogin] CSRF token not found from /templates/oobe/d-device-pick.handlebars
2024-08-08 08:35:30.190 DEBUG (MainThread) [alexapy.alexalogin] No csrf token found
2024-08-08 08:35:30.370 DEBUG (MainThread) [alexapy.alexalogin] GET: 
https://alexa.amazon.com/api/bootstrap returned 401:Unauthorized with response <CIMultiDictProxy('Content-Length': '0', 'Connection': 'keep-alive', 'Server': 'Server', 'Date': 'Thu, 08 Aug 2024 07:35:30 GMT', 'x-amz-rid': '38HE1KF6MKBZV13S8TW4', 'loginUrl': 'https://www.amazon.com/ap/signin?showRmrMe=1&openid.return_to=https%3A%2F%2Falexa.amazon.com%2Flogin&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_dp_project_dee&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&', 'x-amzn-RequestId': '38HE1KF6MKBZV13S8TW4', 'Vary': 'Content-Type,Accept-Encoding,User-Agent', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 ce5dbfaddd5f47651d290bd1692e032e.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MAN50-C3', 'X-Amz-Cf-Id': 'ZlsSejfEeZZIp3aEOwX3ippbopyEJAq6jPOiy5U9nhbgUE8l_7MSVQ==')>
2024-08-08 08:35:30.371 DEBUG (MainThread) [alexapy.alexalogin] Not logged in: An exception of type ContentTypeError occurred. Arguments:
(RequestInfo(url=URL('https://alexa.amazon.com/api/bootstrap'), method='GET', headers=<CIMultiDictProxy('Host': 'alexa.amazon.com', 'User-Agent': 'AmazonWebView/Amazon Alexa/2.2.556530.0/iOS/16.6/iPhone', 'Accept': '*/*', 'Accept-Language': '*', 'DNT': '1', 'Upgrade-Insecure-Requests': '1', 'Accept-Encoding': 'gzip, deflate, br')>, real_url=URL('https://alexa.amazon.com/api/bootstrap')), ())
2024-08-08 08:35:30.405 DEBUG (MainThread) [alexapy.alexalogin] GET: 
https://alexa.amazon.co.uk/api/bootstrap returned 401:Unauthorized with response <CIMultiDictProxy('Content-Length': '0', 'Connection': 'keep-alive', 'Server': 'Server', 'Date': 'Thu, 08 Aug 2024 07:35:30 GMT', 'Strict-Transport-Security': 'max-age=0; includeSubDomains;', 'x-amz-rid': '0085PQ8CW48KFFEQ8JD3', 'loginUrl': 'https://www.amazon.co.uk/ap/signin?showRmrMe=1&openid.return_to=https%3A%2F%2Falexa.amazon.co.uk%2Flogin&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_dp_project_dee_uk&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&', 'x-amzn-RequestId': '0085PQ8CW48KFFEQ8JD3', 'Vary': 'Content-Type,Accept-Encoding,User-Agent', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 90a04b21046e94f26928809a15bdd7ac.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MAN51-P1', 'X-Amz-Cf-Id': 'lcAdYnx5cZH4OUyJSGmx9HVU9VOtaWsZzlAt33Yz2xj0lrIm6-XAvg==')>
2024-08-08 08:35:30.405 DEBUG (MainThread) [alexapy.alexalogin] Not logged in: An exception of type ContentTypeError occurred. Arguments:
(RequestInfo(url=URL('https://alexa.amazon.co.uk/api/bootstrap'), method='GET', headers=<CIMultiDictProxy('Host': 'alexa.amazon.co.uk', 'User-Agent': 'AmazonWebView/Amazon Alexa/2.2.556530.0/iOS/16.6/iPhone', 'Accept': '*/*', 'Accept-Language': '*', 'DNT': '1', 'Upgrade-Insecure-Requests': '1', 'Accept-Encoding': 'gzip, deflate, br', 'Cookie': 'session-id=261-3560783-7746030; session-id-time=2353822530l; session-token="Fe2eY4R01O5iGhlt37YxAb7h388kslT/vEMukbV1w/ttg/G+SwqoPu4j5CQcZdotw4SiVRLHAVzvlgen7y7EUbQkvSC3btrIUu9Y/3nItYwtdqF6WRRl2xwmnBXkca/PobRSb38z+Gpv3JUbOongYElWtPcWllVPtrxJp0zs99TfszQ5n0PDdn/x0xzj+lCktI18uhLvGA4mZjs9gHhS7Q6uSt7KOKhIpUQQGz+JyrVnt5mIgfjPiVIK/YkpwJ0e11z/HEUZvbvP+yAPpVfL4w+YEJzQ7Fb9/L8homtXVCrtuGDSED6nh9wkbIRDHJjM0LW4DSJopIl5M+wRV6nvFWhTdW/nGVZavuUbu+VHvAs="; ubid-acbuk=260-0571959-3157045; ubid-main=260-0571959-3157045')>, real_url=URL('https://alexa.amazon.co.uk/api/bootstrap')), ())
2024-08-08 08:35:30.405 DEBUG (MainThread) [alexapy.alexalogin] Login failed; check credentials
2024-08-08 08:35:30.406 DEBUG (MainThread) [alexapy.alexalogin] Found post url to /errors/validateCaptcha
2024-08-08 08:35:30.406 DEBUG (MainThread) [alexapy.alexalogin] Preparing form submission to /errors/validateCaptcha with input data: {}
2024-08-08 08:35:30.406 DEBUG (MainThread) [alexapy.alexalogin] No 2FA code supplied but will generate.
2024-08-08 08:35:30.406 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP 465600
2024-08-08 08:35:30.407 WARNING (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7fb52b8ceab0>,), {'cookies': {}}): An error occurred accessing AlexaAPI: An exception of type InvalidUrlClientError occurred. Arguments:
(URL('/errors/validateCaptcha'),)
2024-08-08 08:35:30.407 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Alexa for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 359, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 687, in login
    post_resp = await self._session.post(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 576, in _request
    raise err_exc_cls(url)
aiohttp.client_exceptions.InvalidUrlClientError: /errors/validateCaptcha
`

**Additional context**

**Comment by Drewskieza** [comment]
I see a new version has released.
