### ISSUE TITLE
Unable to control devices in Dutch language

### ISSUE THREAD

**Issue by GJurriens** [alandtse/alexa_media_player#2480]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

When an Alexa device is set to Dutch language, you cannot control it or see any status updates. The devices get detected but every entity shows as unavailable

**To Reproduce**

Set a device to use the Dutch language and check after configuring the integration. English language devices are normally detected and are able to be operated, Dutch devices do show up, but all operations are not available

**Expected behavior**

To be able to see the status of and controll when the device is in Dutch language.

**Screenshots**

![image](https://github.com/user-attachments/assets/fa4bfa4c-8490-4e5b-936f-bcba272d25b7)

**System details**

- Home Assistant version: 2024.8.2
- alexa_media version (from `const.py` or HA startup log): 4.12.10
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): yes
- Amazon Domain: amazon.nl

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

Dutch language support has just gone generally available, so maybe that is why it does not work yet.

**Comment by danielbrunt57** [comment]
I think const.py in alexapy might need updating:
```python
LOCALE_KEY = {
    ".de": "de_DE",
    ".com.au": "en_AU",
    ".ca": "en_CA",
    ".co.uk": "en_GB",
    ".in": "en_IN",
    ".com": "en_US",
    ".es": "es_ES",
    ".mx": "es_MX",
    ".fr": "fr_FR",
    ".it": "it_IT",
    ".co.jp": "ja_JP",
    ".com.br": "pt_BR",
}
```

**Comment by GJurriens** [comment]
Thank you for your response danielbrunt57. I have tried adding ".nl": "nl_NL", to the locale key, but that didn't seem to help.

When I check the log, I see the following:
Logger: homeassistant.config_entries
Bron: config_entries.py:604
Eerst voorgekomen: 12:49:51 (1 gebeurtenissen)
Laatst gelogd: 12:49:51

Error setting up entry amazon.nl@guido.jurriens.com - amazon.nl for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 360, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 328, in load_cookie
    cookies = pickle.loads(await myfile.read())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/cookies.py", line 312, in __setitem__
    raise CookieError("Invalid attribute %r" % (K,))
http.cookies.CookieError: Invalid attribute 'partitioned'

**Comment by GJurriens** [comment]
[home-assistant_alexa_media_2024-08-24T10-52-50.335Z.log](https://github.com/user-attachments/files/16736287/home-assistant_alexa_media_2024-08-24T10-52-50.335Z.log)
Also, this is the debug logging.

**Comment by danielbrunt57** [comment]
> File "/usr/local/lib/python3.12/http/cookies.py", line 312, in **setitem**
> raise CookieError("Invalid attribute %r" % (K,))
> http.cookies.CookieError: Invalid attribute 'partitioned'

@GJurriens You need to replace the python3.12/http/cookies.py with the one from Python 3.13 beta PR [gh-112713](https://github.com/python/cpython/pull/112714) which will add support for the new Partitioned attribute in the Morsel object in http.cookies.

**Comment by danielbrunt57** [comment]
@GJurriens Is this still an issue for you on current versions?

**Comment by outsidernl** [comment]
i can confirm this is still an issue on current versions

**Comment by danielbrunt57** [comment]
I'll need to see a fresh set of debug log entries...
