### ISSUE TITLE
Integration stopped working after HA update

### ISSUE THREAD

**Issue by stas1000** [alandtse/alexa_media_player#2614]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After updating HA the integration fails to setup/connect

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/2c580579-b217-400d-9046-1955f2e0c9b8)

**System details**

- Home Assistant version:
- alexa_media version (from `const.py` or HA startup log):
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 19:27:24 (2 occurrences)
Last logged: 19:27:34

Error setting up entry stevestas1000@gmail.com - amazon.com.au for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 713, in login
    self._site = await self._process_page(await post_resp.text(), site)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 1506, in _process_page
    error_message += list_item.find("span").string
TypeError: can only concatenate str (not "NoneType") to str

&

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 19:27:24 (2 occurrences)
Last logged: 19:27:34

Error setting up entry XXXXXX - amazon.com.au for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 713, in login
    self._site = await self._process_page(await post_resp.text(), site)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 1506, in _process_page
    error_message += list_item.find("span").string
TypeError: can only concatenate str (not "NoneType") to str

**Comment by stas1000** [comment]
I restored and old backup and re-updated everything. This fixed the issue
