### ISSUE TITLE
on 4.13.4, it works for a while after re-loading, but then stops announcing

### ISSUE THREAD

**Issue by ik0adr** [alandtse/alexa_media_player#2620]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home Assistant version: 2024.10.2
- alexa_media version (from `const.py` or HA startup log): 4.13.4
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): WARNING: Package(s) not found: alexapy

- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): Y
- Amazon Domain:
amazon.it
**Debug Logs (alexa_media & alexapy)**

2024-10-07 10:00:03.266 WARNING (MainThread) [alexapy.helpers] alexaapi.run_behavior((<alexapy.alexaapi.AlexaAPI object at 0x7f4e9b1e80>, {'@type': 'com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode', 'type': 'AlexaAnnouncement', 'operationPayload': {'deviceType': 'A7WXQPH584YP', 'deviceSerialNumber': 'G************5X5', 'locale': 'it-it', 'customerId': 'A**********MRH', 'expireAfter': 'PT5S', 'content': [{'locale': 'it-it', 'display': {'title': 'Home Assistant', 'body': '"<lang xml:lang=\'it-IT\'> <voice name=\'Giorgio\'>    Sono le 10, e tutto va bene, ",    almeno qui dentro, e di fuori ci frega il giusto...,\n    "</voice> </lang>"'}, 'speak': {'type': 'text', 'value': '"<lang xml:lang=\'it-IT\'> <voice name=\'Giorgio\'>    Sono le 10, e tutto va bene, ",    almeno qui dentro, e di fuori ci frega il giusto...,\n    "</voice> </lang>"'}}], 'target': {'customerId': 'A**********MRH', 'devices': [{'deviceSerialNumber': 'G************5X5', 'deviceTypeId': 'A7WXQPH584YP'}]}, 'skillId': 'amzn1.ask.1p.routines.messaging'}}), {'queue_delay': 1.5}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)

2024-10-07 10:00:03.267 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 960, in send_announcement
    await self.send_sequence(
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 512, in send_sequence
    await self.run_behavior(node_data, queue_delay=queue_delay)
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 434, in run_behavior
    await self._post_request("/api/behaviors/preview", data=data)
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 226, in _post_request
    return await self._request("post", uri, data, query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 199, in _request
    raise AlexapyLoginError("Login error detected; not contacting API")
alexapy.errors.AlexapyLoginError: Login error detected; not contacting API

Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by cagnulein** [comment]
@ik0adr how did you get working on amazon.it after the issue on august? i'm still always getting a 500 error after the captcha.
Thanks
