### ISSUE TITLE
HA freezes when using latest AMP

### ISSUE THREAD

**Issue by victoroos** [alandtse/alexa_media_player#2622]
**Describe the bug**

After reinstalling AMP after the memroy overload bug which was fixed very fast I noticed  after a day or 2 all of a sudden my HA stopped responding completely

**System details**

- Home Assistant version: 2024.10.2
- alexa_media version (from `const.py` or HA startup log): [4.13.4](https://github.com/alandtse/alexa_media_player/releases/tag/v4.13.4)
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 1.29.2
- Is Amazon [2FA/2SV enabled Yyes
- Amazon Domain: 

**Debug Logs (alexa_media & alexapy)**
2024-10-11 00:15:09.521 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f9273f10450>,) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 922: http2 = HTTP2EchoClient( (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/alandtse/alexa_media_player/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alexa_media/__init__.py", line 363, in async_setup_entry
    await setup_alexa(hass, config_entry, login)
  File "/config/custom_components/alexa_media/__init__.py", line 1312, in setup_alexa
    await http2_connect()
  File "/config/custom_components/alexa_media/__init__.py", line 922, in http2_connect
    http2 = HTTP2EchoClient(

**Additional context**

I can't find a fix for it

**Comment by z-master42** [comment]
Why do you think AMP is the cause of this? The warning has been there for months and is just a warning and not an error.

**Comment by victoroos** [comment]
> Why do you think AMP is the cause of this? The warning has been there for months and is just a warning and not an error.

Cause everytime when I enable the extension HA freezes. Hmm then I should find something else in the log?
