### ISSUE TITLE
Detected blocking call to load_verify_locations with args

### ISSUE THREAD

**Issue by Impedanz** [alandtse/alexa_media_player#2625]
**Describe the bug**

Does anyone know what this is? Please forgive me if I don't have an exact description. No error occurs during use, but this is displayed in the log.

```
Logger: homeassistant.util.loop
Quelle: util/loop.py:136
Erstmals aufgetreten: 13:03:37 (4 Vorkommnisse)
Zuletzt protokolliert: 13:03:40

Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fdf3c8a7450>, '/usr/local/lib/python3.12/site-packages/certifi/cacert.pem', None, None) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 341: AlexaLogin( (offender: /usr/local/lib/python3.12/ssl.py, line 708: context.load_verify_locations(cafile, capath, cadata)), please create a bug report at https://github.com/alandtse/alexa_media_player/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/alexa_media/__init__.py", line 341, in async_setup_entry AlexaLogin(
Detected blocking call to open with args (PosixPath('/config/.storage/alexa_media.c.eissenhardt@gmx.de.pickle'),) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 361: await login.login(cookies=await login.load_cookie()) (offender: /usr/local/lib/python3.12/site-packages/aiohttp/cookiejar.py, line 126: with file_path.open(mode="rb") as f:), please create a bug report at https://github.com/alandtse/alexa_media_player/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry await login.login(cookies=await login.load_cookie())
Detected blocking call to open with args (PosixPath('/config/.storage/alexa_media.c.eissenhardt@gmx.de.pickle'),) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 361: await login.login(cookies=await login.load_cookie()) (offender: /usr/local/lib/python3.12/site-packages/aiohttp/cookiejar.py, line 121: with file_path.open(mode="wb") as f:), please create a bug report at https://github.com/alandtse/alexa_media_player/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry await login.login(cookies=await login.load_cookie())
Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fdf3c7c2750>,) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 922: http2 = HTTP2EchoClient( (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/alandtse/alexa_media_player/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/alexa_media/__init__.py", line 363, in async_setup_entry await setup_alexa(hass, config_entry, login) File "/config/custom_components/alexa_media/__init__.py", line 1312, in setup_alexa await http2_connect() File "/config/custom_components/alexa_media/__init__.py", line 922, in http2_connect http2 = HTTP2EchoClient(
```

**System details**

- Home Assistant version: 
Core 2024.10.2
Supervisor 2024.10.2
Operating System 13.1
Frontend 20241002.3

- alexa_media version (from `const.py` or HA startup log):
4.13.4

- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): Yes, No Login Problems
![AlexaMediaPlayer](https://github.com/user-attachments/assets/2f9fad2b-cc00-4bd3-967f-1b466319a547)

**Comment by trippo** [comment]
Same bug here

**Comment by Impedanz** [comment]
for this loop it exist an work arround... Register Account, try to register your existing account Mail, than it says "ey you got one" and then login. DONT FORGET!! If you from Germany... use .DE Domain! etc etc,...

**Comment by trippo** [comment]
You are right!! after that trick the from contain email and password in the same page and work fine...

Thank you a lot @Impedanz

**Comment by krissen** [comment]
Same errors in the log here.

**Comment by CGU1969** [comment]
I have the same problem, and the workarround said by @Impedanz, don't work for me.

**Comment by CGU1969** [comment]
With the new version 4.13.5, the issue has been resolved. I needed several attempts to install AMP, but it was finally fixed.

Thanks you very much for the update!!!

**Comment by danielbrunt57** [comment]
> **Describe the bug**
> 
> Does anyone know what this is? Please forgive me if I don't have an exact description. No error occurs during use, but this is displayed in the log.
> 
> ```
> Logger: homeassistant.util.loop
> Quelle: util/loop.py:136
> Erstmals aufgetreten: 13:03:37 (4 Vorkommnisse)
> Zuletzt protokolliert: 13:03:40
> 
> Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fdf3c8a7450>, '/usr/local/lib/python3.12/site-packages/certifi/cacert.pem', None, None) inside the event loop by custom integration 'alexa_media' at custom_components/alexa_media/__init__.py, line 341: AlexaLogin( 
(offender: /usr/local/lib/python3.12/ssl.py, line 708: context.load_verify_locations(cafile, capath, cadata))

I've finally managed to solve this last remaining WARNING!  
It was being triggered by another library written by @alandtse which `alexapy/alexaproxy.py` imports: `authcaptureproxy`.

I've modified it to preload the ssl default context and the warning is now gone:
```
2024-11-27 23:48:41.897 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating new AlexaProxy...
2024-11-27 23:48:41.897 DEBUG (MainThread) [alexapy.alexalogin] Attempting oauth login to https://www.amazon.com/ap/register?openid.return_to=https://www.amazon.com/ap/maplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:333163653539353339633431616663626666303737346466613435653763666632333431333234393536346335363335353634643332353733383331&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.response_type=code&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access+offline_access&openid.oa2.code_challenge_method=S256&openid.oa2.code_challenge=4A0mojJS1Os1mJIQL8HDGOweedsiH87JUiYXf5Xl2-M&language=en_CA...
2024-11-27 23:48:41.899 DEBUG (MainThread) [alexapy.alexalogin] Returning site:  https://www.amazon.com/ap/register?openid.return_to=https://www.amazon.com/ap/maplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:333163653539353339633431616663626666303737346466613435653763666632333431333234393536346335363335353634643332353733383331&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.response_type=code&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access+offline_access&openid.oa2.code_challenge_method=S256&openid.oa2.code_challenge=4A0mojJS1Os1mJIQL8HDGOweedsiH87JUiYXf5Xl2-M&language=en_CA

============================== !!!  No more WARNING  !!!  =================================
2024-11-27 23:48:41.899 DEBUG (MainThread) [httpx] load_ssl_context verify=<ssl.SSLContext object at 0xfffee30caf50> cert=None trust_env=True http2=False
=================================================================================

2024-11-27 23:48:41.900 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP 575508
2024-11-27 23:48:41.900 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Refreshed 2 modifiers: ['prepend_relative_urls', 'change_host_to_proxy']
```

`/usr/local/lib/python3.12/site-packages/authcaptureproxy/auth_capture_proxy.py`:
```
#  SPDX-License-Identifier: Apache-2.0
"""Python Package for auth capture proxy."""
import asyncio
import logging
import re
from functools import partial
from ssl import SSLContext
from ssl import create_default_context        # <=== Added
from typing import Any, Callable, Dict, List, Optional, Text, Tuple, Union

import httpx
from httpx import AsyncClient

from aiohttp import (
    ClientConnectionError,
    MultipartReader,
    MultipartWriter,
    TooManyRedirects,
    hdrs,
    web,
)
from multidict import CIMultiDict
from yarl import URL

from authcaptureproxy.const import SKIP_AUTO_HEADERS
from authcaptureproxy.examples.modifiers import (
    prepend_relative_urls,
    replace_empty_action_urls,
    replace_matching_urls,
)
from authcaptureproxy.helper import (
    convert_multidict_to_dict,
    get_content_type,
    get_nested_dict_keys,
    print_resp,
    run_func,
    swap_url,
)
from authcaptureproxy.stackoverflow import get_open_port

# Pre-configure SSL context                   <=== Added
ssl_context = create_default_context()   <===  2024-11-28

_LOGGER = logging.getLogger(__name__)


class AuthCaptureProxy:
    """Class to handle proxy login connections.

    This class relies on tests to be provided to indicate the proxy has completed. At proxy completion all data can be found in self.session, self.data, and sel
    """

    def __init__(
        self,
        proxy_url: URL,
        host_url: URL,
        session: Optional[httpx.AsyncClient] = None,
        session_factory: Optional[Callable[[], httpx.AsyncClient]] = None,
        preserve_headers: bool = False,
    ) -> None:
        """Initialize proxy object.

        Args:
            proxy_url (URL): url for proxy location. e.g., http://192.168.1.1/. If there is any path, the path is considered part of the base url. If no explici
            host_url (URL): original url for login, e.g., http://amazon.com
            session (httpx.AsyncClient): httpx client to make queries. Optional
            session_factory (lambda: httpx.AsyncClient): factory to create the aforementioned httpx client if having one fixed session is insufficient.
            preserve_headers (bool): Whether to preserve headers from the backend. Useful in circumventing CSRF protection. Defaults to False.
        """
        self._preserve_headers = preserve_headers
        self.session_factory: Callable[[], httpx.AsyncClient] = session_factory or (
            #lambda: httpx.AsyncClient()                                                                  <=== Original code
            lambda: httpx.AsyncClient(verify=ssl_context)                                     # <=== Modification
        )
```
