### ISSUE TITLE
Repeat Login necessary

### ISSUE THREAD

**Issue by ThiloAm** [alandtse/alexa_media_player#2686]
**After restarting Home Assistant, authentication needs to be performed again and _remains valid only until the next restart_.**

**Extract from the log:**
```
Logger: homeassistant.components.media_player
Quelle: helpers/entity_platform.py:365
Integration: Mediaplayer (Dokumentation, Probleme)
Erstmals aufgetreten: 12:56:07 (1 Vorkommnisse)
Zuletzt protokolliert: 12:56:07

Error while setting up jellyfin platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/src/homeassistant/homeassistant/components/jellyfin/media_player.py", line 46, in async_setup_entry
    handle_coordinator_update()
  File "/usr/src/homeassistant/homeassistant/components/jellyfin/media_player.py", line 40, in handle_coordinator_update
    entity: MediaPlayerEntity = JellyfinMediaPlayer(coordinator, session_id)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/jellyfin/media_player.py", line 60, in __init__
    super().__init__(coordinator, session_id)
  File "/usr/src/homeassistant/homeassistant/components/jellyfin/entity.py", line 47, in __init__
    self.device_name: str = self.session_data["DeviceName"]
                            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'DeviceName'

```

### Alexa Media Player 4.13.8

Core				2024.11.2
Supervisor 			2024.11.2
Operating System 	 13.2
Frontend			20241106.2

**Comment by danielbrunt57** [comment]
That error is a new one on me!
I did find this core issue from Feb 3/24: [Jellyfin Integration fails with "KeyError: 'DeviceName'" #109532](https://github.com/home-assistant/core/issues/109532)
