### ISSUE TITLE
module 'pyotp' has no attribute 'TOTP

### ISSUE THREAD

**Issue by matte-oss** [alandtse/alexa_media_player#2749]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

When booting my home assistant instance i get the error below and AMP will not boot.
I think this started happening in 2024.12.3

**To Reproduce**

1. Boot home Assistant
2. See error

**Expected behavior**

AMP boots correctly

**Screenshots**

**System details**

- Home Assistant version: 2024.12.3
- alexa_media version (from `const.py` or HA startup log): 5.0.4
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y 
- Amazon Domain: Amazon.it

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

```
Setup failed for custom integration 'alexa_media': Unable to import component: Exception importing custom_components.alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 18, in <module>
    from alexapy import (
    ...<9 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/alexapy/__init__.py", line 17, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.13/site-packages/alexapy/alexaapi.py", line 24, in <module>
    from .alexalogin import AlexaLogin
  File "/usr/local/lib/python3.13/site-packages/alexapy/alexalogin.py", line 76, in <module>
    class AlexaLogin:
    ...<1703 lines>...
            self._headers.pop("Content-Type", None)
  File "/usr/local/lib/python3.13/site-packages/alexapy/alexalogin.py", line 263, in AlexaLogin
    def set_totp(self, otp_secret: str) -> Optional[pyotp.TOTP]:
                                                    ^^^^^^^^^^
AttributeError: module 'pyotp' has no attribute 'TOTP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.alexa_media

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 18, in <module>
    from alexapy import (
    ...<9 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/alexapy/__init__.py", line 17, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.13/site-packages/alexapy/alexaapi.py", line 24, in <module>
    from .alexalogin import AlexaLogin
  File "/usr/local/lib/python3.13/site-packages/alexapy/alexalogin.py", line 76, in <module>
    class AlexaLogin:
    ...<1703 lines>...
            self._headers.pop("Content-Type", None)
  File "/usr/local/lib/python3.13/site-packages/alexapy/alexalogin.py", line 263, in AlexaLogin
    def set_totp(self, otp_secret: str) -> Optional[pyotp.TOTP]:
                                                    ^^^^^^^^^^
AttributeError: module 'pyotp' has no attribute 'TOTP'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.alexa_media

```

**Additional context**

**Comment by matte-oss** [comment]
Fixed itself after an hard reboot
