### ISSUE TITLE
Unable to install Alexa integration

### ISSUE THREAD

**Issue by mtchecker** [alandtse/alexa_media_player#2771]
**Describe the bug**

Alexa integration can not be installed

**To Reproduce**

After adding the repository in HACS and installing the integration via HA and error occurs.

1. Go to 'Devices and Services'
2. Click on 'Add integration'
3. Scroll down to 'Alexa media player'

**Expected behavior**

Installation starts

**Screenshots**

![grafik](https://github.com/user-attachments/assets/4268ad9c-c979-434b-b693-77a93c97b484)

**System details**

- Home Assistant version:
Core 2024.12.5
Supervisor 2024.12.0
Operating System 14.1
Frontend 20241127.8
- alexa_media version (from `const.py` or HA startup log): v5.2.0
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

Log1:

> Logger: homeassistant.loader
Quelle: loader.py:1271
Erstmals aufgetreten: 15:27:34 (4 Vorkommnisse)
Zuletzt protokolliert: 15:36:33
Unexpected exception importing platform custom_components.alexa_media.config_flow

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1271, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1303, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 18, in <module>
    from alexapy import (
    ...<9 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/alexapy/__init__.py", line 17, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.13/site-packages/alexapy/alexaapi.py", line 24, in <module>
    from .alexalogin import AlexaLogin
  File "/usr/local/lib/python3.13/site-packages/alexapy/alexalogin.py", line 76, in <module>
    class AlexaLogin:
    ...<1703 lines>...
            self._headers.pop("Content-Type", None)
  File "/usr/local/lib/python3.13/site-packages/alexapy/alexalogin.py", line 263, in AlexaLogin
    def set_totp(self, otp_secret: str) -> Optional[pyotp.TOTP]:
                                                    ^^^^^^^^^^
AttributeError: module 'pyotp' has no attribute 'TOTP'

Log2:

> Logger: homeassistant.config_entries
Quelle: config_entries.py:3314
Erstmals aufgetreten: 15:27:34 (2 Vorkommnisse)
Zuletzt protokolliert: 15:36:33
Error occurred loading flow for integration alexa_media: Exception importing custom_components.alexa_media.config_flow

**Comment by danielbrunt57** [comment]
"After adding the repository in HACS and installing the integration via HA and error occurs." 
Did you restart HA **TWICE** before trying to install the integration?

**Comment by mtchecker** [comment]
HA was restarted several times without a difference.
Executing pip show pyotp and pip show alexapy show "command not found":
![grafik](https://github.com/user-attachments/assets/eca64d84-aecc-4914-a8a1-bbefca2c038c)

**Comment by danielbrunt57** [comment]
You can't do it from there!  You have to get into the `homeassistant` container:

![image](https://github.com/user-attachments/assets/6803a686-33ac-403c-b997-3c6ced85a9c9)

**Comment by mtchecker** [comment]
Is there a tutorial or a instruction how to get into the homeassistant container?
When entering the commands you wrote I won't get the correct response:
![grafik](https://github.com/user-attachments/assets/6f15889a-23dc-4c0a-9c5e-4c0898aab5a3)

**Comment by danielbrunt57** [comment]
Are you using this add-on?

![image](https://github.com/user-attachments/assets/9cc3bc29-3ec0-4790-8fd2-15a98b3ad495)

![image](https://github.com/user-attachments/assets/1695be03-c381-47cb-a160-32b0c3c104f6)

**Comment by mtchecker** [comment]
I used the offical Add-on and now installed the advanced SSH.
With this I am able to read out and it seems that alexapy is not installed:
![grafik](https://github.com/user-attachments/assets/57ebfc7a-b655-46b7-a3c4-8192e3ae1f92)

How can I install this?

**Comment by danielbrunt57** [comment]
`pip install alexapy`

**Comment by mtchecker** [comment]
With that now it finally works! Thank you very much!
